/*
Copyright © 2020 ConsenSys

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package rollup

import (
	"testing"

	"github.com/consensys/gnark-crypto/ecc"
	"github.com/consensys/gnark/frontend"
	"github.com/consensys/gnark/std/hash/mimc"
	"github.com/consensys/gnark/test"
	"github.com/iotaledger/trie.go/models/trie_mimc"
)

type circuitSignature Circuit

// Circuit implements part of the rollup circuit only by delcaring a subset of the constraints
func (t *circuitSignature) Define(api frontend.API) error {
	if err := (*Circuit)(t).postInit(api); err != nil {
		return err
	}
	hFunc, err := mimc.NewMiMC(api)
	if err != nil {
		return err
	}
	return verifyTransferSignature(api, t.Transfers[0], hFunc)
}

func TestCircuitSignature(t *testing.T) {

	const nbAccounts = 10

	operator, users := createOperator(nbAccounts)

	// read accounts involved in the transfer
	sender, err := operator.readAccount(0)
	if err != nil {
		t.Fatal(err)
	}

	receiver, err := operator.readAccount(1)
	if err != nil {
		t.Fatal(err)
	}

	// create the transfer and sign it
	amount := uint64(10)
	transfer := NewTransfer(amount, sender.pubKey, receiver.pubKey, sender.nonce)

	// sign the transfer
	_, err = transfer.Sign(users[0], operator.h)
	if err != nil {
		t.Fatal(err)
	}

	// update the state from the received transfer
	err = operator.updateState(transfer, 0)
	if err != nil {
		t.Fatal(err)
	}

	// verifies the signature of the transfer
	assert := test.NewAssert(t)

	var signatureCircuit circuitSignature
	assert.ProverSucceeded(&signatureCircuit, &operator.witnesses, test.WithCurves(ecc.BN254), test.WithCompileOpts(frontend.IgnoreUnconstrainedInputs()))

}

type circuitInclusionProof Circuit

// Circuit implements part of the rollup circuit only by delcaring a subset of the constraints
func (t *circuitInclusionProof) Define(api frontend.API) error {
	if err := (*Circuit)(t).postInit(api); err != nil {
		return err
	}
	hashFunc, err := mimc.NewMiMC(api)
	if err != nil {
		return err
	}

	trie_mimc.Validate256(api, hashFunc, t.TrieRootHashesBefore[0],
		t.TrieProofsSenderBefore[0][0][:],
		t.TrieProofsSenderBefore[0][1][:],
		t.TrieProofsSenderBefore[0][2][:],
		t.TrieProofsSenderBefore[0][3][:],
		t.TrieProofsSenderBefore[0][4][:],
		t.TrieProofsSenderBefore[0][5][:],
		t.TrieProofsSenderBefore[0][6][:],
		t.TrieProofsSenderBefore[0][7][:],
		t.TrieProofsSenderBefore[0][8][:],
		t.TrieProofsSenderBefore[0][9][:],
		t.TrieProofsSenderBefore[0][10][:],
		t.TrieProofsSenderBefore[0][11][:],
		t.TrieProofsSenderBefore[0][12][:],
		t.TrieProofsSenderBefore[0][13][:],
		t.TrieProofsSenderBefore[0][14][:],
		t.TrieProofsSenderBefore[0][15][:],
		t.TrieProofsSenderBefore[0][16][:],
		t.TrieProofsSenderBefore[0][17][:],
		t.TrieProofsSenderBefore[0][18][:],
		t.TrieProofsSenderBefore[0][19][:],
		t.TrieProofsSenderBefore[0][20][:],
		t.TrieProofsSenderBefore[0][21][:],
		t.TrieProofsSenderBefore[0][22][:],
		t.TrieProofsSenderBefore[0][23][:],
		t.TrieProofsSenderBefore[0][24][:],
		t.TrieProofsSenderBefore[0][25][:],
		t.TrieProofsSenderBefore[0][26][:],
		t.TrieProofsSenderBefore[0][27][:],
		t.TrieProofsSenderBefore[0][28][:],
		t.TrieProofsSenderBefore[0][29][:],
		t.TrieProofsSenderBefore[0][30][:],
		t.TrieProofsSenderBefore[0][31][:],
		t.TrieProofsSenderBefore[0][32][:],
		t.TrieProofsSenderBefore[0][33][:],
		t.TrieProofsSenderBefore[0][34][:],
		t.TrieProofsSenderBefore[0][35][:],
		t.TrieProofsSenderBefore[0][36][:],
		t.TrieProofsSenderBefore[0][37][:],
		t.TrieProofsSenderBefore[0][38][:],
		t.TrieProofsSenderBefore[0][39][:],
		t.TrieProofsSenderBefore[0][40][:],
		t.TrieProofsSenderBefore[0][41][:],
		t.TrieProofsSenderBefore[0][42][:],
		t.TrieProofsSenderBefore[0][43][:],
		t.TrieProofsSenderBefore[0][44][:],
		t.TrieProofsSenderBefore[0][45][:],
		t.TrieProofsSenderBefore[0][46][:],
		t.TrieProofsSenderBefore[0][47][:],
		t.TrieProofsSenderBefore[0][48][:],
		t.TrieProofsSenderBefore[0][49][:],
		t.TrieProofsSenderBefore[0][50][:],
		t.TrieProofsSenderBefore[0][51][:],
		t.TrieProofsSenderBefore[0][52][:],
		t.TrieProofsSenderBefore[0][53][:],
		t.TrieProofsSenderBefore[0][54][:],
		t.TrieProofsSenderBefore[0][55][:],
		t.TrieProofsSenderBefore[0][56][:],
		t.TrieProofsSenderBefore[0][57][:],
		t.TrieProofsSenderBefore[0][58][:],
		t.TrieProofsSenderBefore[0][59][:],
		t.TrieProofsSenderBefore[0][60][:],
		t.TrieProofsSenderBefore[0][61][:],
		t.TrieProofsSenderBefore[0][62][:],
		t.TrieProofsSenderBefore[0][63][:],
		t.TrieProofsSenderBefore[0][64][:],
		t.TrieProofsSenderBefore[0][65][:],
		t.TrieProofsSenderBefore[0][66][:],
		t.TrieProofsSenderBefore[0][67][:],
		t.TrieProofsSenderBefore[0][68][:],
		t.TrieProofsSenderBefore[0][69][:],
		t.TrieProofsSenderBefore[0][70][:],
		t.TrieProofsSenderBefore[0][71][:],
		t.TrieProofsSenderBefore[0][72][:],
		t.TrieProofsSenderBefore[0][73][:],
		t.TrieProofsSenderBefore[0][74][:],
		t.TrieProofsSenderBefore[0][75][:],
		t.TrieProofsSenderBefore[0][76][:],
		t.TrieProofsSenderBefore[0][77][:],
		t.TrieProofsSenderBefore[0][78][:],
		t.TrieProofsSenderBefore[0][79][:],
		t.TrieProofsSenderBefore[0][80][:],
		t.TrieProofsSenderBefore[0][81][:],
		t.TrieProofsSenderBefore[0][82][:],
		t.TrieProofsSenderBefore[0][83][:],
		t.TrieProofsSenderBefore[0][84][:],
		t.TrieProofsSenderBefore[0][85][:],
		t.TrieProofsSenderBefore[0][86][:],
		t.TrieProofsSenderBefore[0][87][:],
		t.TrieProofsSenderBefore[0][88][:],
		t.TrieProofsSenderBefore[0][89][:],
		t.TrieProofsSenderBefore[0][90][:],
		t.TrieProofsSenderBefore[0][91][:],
		t.TrieProofsSenderBefore[0][92][:],
		t.TrieProofsSenderBefore[0][93][:],
		t.TrieProofsSenderBefore[0][94][:],
		t.TrieProofsSenderBefore[0][95][:],
		t.TrieProofsSenderBefore[0][96][:],
		t.TrieProofsSenderBefore[0][97][:],
		t.TrieProofsSenderBefore[0][98][:],
		t.TrieProofsSenderBefore[0][99][:],
		t.TrieProofsSenderBefore[0][100][:],
		t.TrieProofsSenderBefore[0][101][:],
		t.TrieProofsSenderBefore[0][102][:],
		t.TrieProofsSenderBefore[0][103][:],
		t.TrieProofsSenderBefore[0][104][:],
		t.TrieProofsSenderBefore[0][105][:],
		t.TrieProofsSenderBefore[0][106][:],
		t.TrieProofsSenderBefore[0][107][:],
		t.TrieProofsSenderBefore[0][108][:],
		t.TrieProofsSenderBefore[0][109][:],
		t.TrieProofsSenderBefore[0][110][:],
		t.TrieProofsSenderBefore[0][111][:],
		t.TrieProofsSenderBefore[0][112][:],
		t.TrieProofsSenderBefore[0][113][:],
		t.TrieProofsSenderBefore[0][114][:],
		t.TrieProofsSenderBefore[0][115][:],
		t.TrieProofsSenderBefore[0][116][:],
		t.TrieProofsSenderBefore[0][117][:],
		t.TrieProofsSenderBefore[0][118][:],
		t.TrieProofsSenderBefore[0][119][:],
		t.TrieProofsSenderBefore[0][120][:],
		t.TrieProofsSenderBefore[0][121][:],
		t.TrieProofsSenderBefore[0][122][:],
		t.TrieProofsSenderBefore[0][123][:],
		t.TrieProofsSenderBefore[0][124][:],
		t.TrieProofsSenderBefore[0][125][:],
		t.TrieProofsSenderBefore[0][126][:],
		t.TrieProofsSenderBefore[0][127][:],
		t.TrieProofsSenderBefore[0][128][:],
		t.TrieProofsSenderBefore[0][129][:],
		t.TrieProofsSenderBefore[0][130][:],
		t.TrieProofsSenderBefore[0][131][:],
		t.TrieProofsSenderBefore[0][132][:],
		t.TrieProofsSenderBefore[0][133][:],
		t.TrieProofsSenderBefore[0][134][:],
		t.TrieProofsSenderBefore[0][135][:],
		t.TrieProofsSenderBefore[0][136][:],
		t.TrieProofsSenderBefore[0][137][:],
		t.TrieProofsSenderBefore[0][138][:],
		t.TrieProofsSenderBefore[0][139][:],
		t.TrieProofsSenderBefore[0][140][:],
		t.TrieProofsSenderBefore[0][141][:],
		t.TrieProofsSenderBefore[0][142][:],
		t.TrieProofsSenderBefore[0][143][:],
		t.TrieProofsSenderBefore[0][144][:],
		t.TrieProofsSenderBefore[0][145][:],
		t.TrieProofsSenderBefore[0][146][:],
		t.TrieProofsSenderBefore[0][147][:],
		t.TrieProofsSenderBefore[0][148][:],
		t.TrieProofsSenderBefore[0][149][:],
		t.TrieProofsSenderBefore[0][150][:],
		t.TrieProofsSenderBefore[0][151][:],
		t.TrieProofsSenderBefore[0][152][:],
		t.TrieProofsSenderBefore[0][153][:],
		t.TrieProofsSenderBefore[0][154][:],
		t.TrieProofsSenderBefore[0][155][:],
		t.TrieProofsSenderBefore[0][156][:],
		t.TrieProofsSenderBefore[0][157][:],
		t.TrieProofsSenderBefore[0][158][:],
		t.TrieProofsSenderBefore[0][159][:],
		t.TrieProofsSenderBefore[0][160][:],
		t.TrieProofsSenderBefore[0][161][:],
		t.TrieProofsSenderBefore[0][162][:],
		t.TrieProofsSenderBefore[0][163][:],
		t.TrieProofsSenderBefore[0][164][:],
		t.TrieProofsSenderBefore[0][165][:],
		t.TrieProofsSenderBefore[0][166][:],
		t.TrieProofsSenderBefore[0][167][:],
		t.TrieProofsSenderBefore[0][168][:],
		t.TrieProofsSenderBefore[0][169][:],
		t.TrieProofsSenderBefore[0][170][:],
		t.TrieProofsSenderBefore[0][171][:],
		t.TrieProofsSenderBefore[0][172][:],
		t.TrieProofsSenderBefore[0][173][:],
		t.TrieProofsSenderBefore[0][174][:],
		t.TrieProofsSenderBefore[0][175][:],
		t.TrieProofsSenderBefore[0][176][:],
		t.TrieProofsSenderBefore[0][177][:],
		t.TrieProofsSenderBefore[0][178][:],
		t.TrieProofsSenderBefore[0][179][:],
		t.TrieProofsSenderBefore[0][180][:],
		t.TrieProofsSenderBefore[0][181][:],
		t.TrieProofsSenderBefore[0][182][:],
		t.TrieProofsSenderBefore[0][183][:],
		t.TrieProofsSenderBefore[0][184][:],
		t.TrieProofsSenderBefore[0][185][:],
		t.TrieProofsSenderBefore[0][186][:],
		t.TrieProofsSenderBefore[0][187][:],
		t.TrieProofsSenderBefore[0][188][:],
		t.TrieProofsSenderBefore[0][189][:],
		t.TrieProofsSenderBefore[0][190][:],
		t.TrieProofsSenderBefore[0][191][:],
		t.TrieProofsSenderBefore[0][192][:],
		t.TrieProofsSenderBefore[0][193][:],
		t.TrieProofsSenderBefore[0][194][:],
		t.TrieProofsSenderBefore[0][195][:],
		t.TrieProofsSenderBefore[0][196][:],
		t.TrieProofsSenderBefore[0][197][:],
		t.TrieProofsSenderBefore[0][198][:],
		t.TrieProofsSenderBefore[0][199][:],
		t.TrieProofsSenderBefore[0][200][:],
		t.TrieProofsSenderBefore[0][201][:],
		t.TrieProofsSenderBefore[0][202][:],
		t.TrieProofsSenderBefore[0][203][:],
		t.TrieProofsSenderBefore[0][204][:],
		t.TrieProofsSenderBefore[0][205][:],
		t.TrieProofsSenderBefore[0][206][:],
		t.TrieProofsSenderBefore[0][207][:],
		t.TrieProofsSenderBefore[0][208][:],
		t.TrieProofsSenderBefore[0][209][:],
		t.TrieProofsSenderBefore[0][210][:],
		t.TrieProofsSenderBefore[0][211][:],
		t.TrieProofsSenderBefore[0][212][:],
		t.TrieProofsSenderBefore[0][213][:],
		t.TrieProofsSenderBefore[0][214][:],
		t.TrieProofsSenderBefore[0][215][:],
		t.TrieProofsSenderBefore[0][216][:],
		t.TrieProofsSenderBefore[0][217][:],
		t.TrieProofsSenderBefore[0][218][:],
		t.TrieProofsSenderBefore[0][219][:],
		t.TrieProofsSenderBefore[0][220][:],
		t.TrieProofsSenderBefore[0][221][:],
		t.TrieProofsSenderBefore[0][222][:],
		t.TrieProofsSenderBefore[0][223][:],
		t.TrieProofsSenderBefore[0][224][:],
		t.TrieProofsSenderBefore[0][225][:],
		t.TrieProofsSenderBefore[0][226][:],
		t.TrieProofsSenderBefore[0][227][:],
		t.TrieProofsSenderBefore[0][228][:],
		t.TrieProofsSenderBefore[0][229][:],
		t.TrieProofsSenderBefore[0][230][:],
		t.TrieProofsSenderBefore[0][231][:],
		t.TrieProofsSenderBefore[0][232][:],
		t.TrieProofsSenderBefore[0][233][:],
		t.TrieProofsSenderBefore[0][234][:],
		t.TrieProofsSenderBefore[0][235][:],
		t.TrieProofsSenderBefore[0][236][:],
		t.TrieProofsSenderBefore[0][237][:],
		t.TrieProofsSenderBefore[0][238][:],
		t.TrieProofsSenderBefore[0][239][:],
		t.TrieProofsSenderBefore[0][240][:],
		t.TrieProofsSenderBefore[0][241][:],
		t.TrieProofsSenderBefore[0][242][:],
		t.TrieProofsSenderBefore[0][243][:],
		t.TrieProofsSenderBefore[0][244][:],
		t.TrieProofsSenderBefore[0][245][:],
		t.TrieProofsSenderBefore[0][246][:],
		t.TrieProofsSenderBefore[0][247][:],
		t.TrieProofsSenderBefore[0][248][:],
		t.TrieProofsSenderBefore[0][249][:],
		t.TrieProofsSenderBefore[0][250][:],
		t.TrieProofsSenderBefore[0][251][:],
		t.TrieProofsSenderBefore[0][252][:],
		t.TrieProofsSenderBefore[0][253][:],
		t.TrieProofsSenderBefore[0][254][:],
		t.TrieProofsSenderBefore[0][255][:],
		t.TrieProofsSenderBefore[0][256][:],
		t.TrieProofsSenderBefore[0][257][:],
		t.TriePathSenderBefore[0][:])
	trie_mimc.Validate256(api, hashFunc, t.TrieRootHashesBefore[0],
		t.TrieProofsReceiverBefore[0][0][:],
		t.TrieProofsReceiverBefore[0][1][:],
		t.TrieProofsReceiverBefore[0][2][:],
		t.TrieProofsReceiverBefore[0][3][:],
		t.TrieProofsReceiverBefore[0][4][:],
		t.TrieProofsReceiverBefore[0][5][:],
		t.TrieProofsReceiverBefore[0][6][:],
		t.TrieProofsReceiverBefore[0][7][:],
		t.TrieProofsReceiverBefore[0][8][:],
		t.TrieProofsReceiverBefore[0][9][:],
		t.TrieProofsReceiverBefore[0][10][:],
		t.TrieProofsReceiverBefore[0][11][:],
		t.TrieProofsReceiverBefore[0][12][:],
		t.TrieProofsReceiverBefore[0][13][:],
		t.TrieProofsReceiverBefore[0][14][:],
		t.TrieProofsReceiverBefore[0][15][:],
		t.TrieProofsReceiverBefore[0][16][:],
		t.TrieProofsReceiverBefore[0][17][:],
		t.TrieProofsReceiverBefore[0][18][:],
		t.TrieProofsReceiverBefore[0][19][:],
		t.TrieProofsReceiverBefore[0][20][:],
		t.TrieProofsReceiverBefore[0][21][:],
		t.TrieProofsReceiverBefore[0][22][:],
		t.TrieProofsReceiverBefore[0][23][:],
		t.TrieProofsReceiverBefore[0][24][:],
		t.TrieProofsReceiverBefore[0][25][:],
		t.TrieProofsReceiverBefore[0][26][:],
		t.TrieProofsReceiverBefore[0][27][:],
		t.TrieProofsReceiverBefore[0][28][:],
		t.TrieProofsReceiverBefore[0][29][:],
		t.TrieProofsReceiverBefore[0][30][:],
		t.TrieProofsReceiverBefore[0][31][:],
		t.TrieProofsReceiverBefore[0][32][:],
		t.TrieProofsReceiverBefore[0][33][:],
		t.TrieProofsReceiverBefore[0][34][:],
		t.TrieProofsReceiverBefore[0][35][:],
		t.TrieProofsReceiverBefore[0][36][:],
		t.TrieProofsReceiverBefore[0][37][:],
		t.TrieProofsReceiverBefore[0][38][:],
		t.TrieProofsReceiverBefore[0][39][:],
		t.TrieProofsReceiverBefore[0][40][:],
		t.TrieProofsReceiverBefore[0][41][:],
		t.TrieProofsReceiverBefore[0][42][:],
		t.TrieProofsReceiverBefore[0][43][:],
		t.TrieProofsReceiverBefore[0][44][:],
		t.TrieProofsReceiverBefore[0][45][:],
		t.TrieProofsReceiverBefore[0][46][:],
		t.TrieProofsReceiverBefore[0][47][:],
		t.TrieProofsReceiverBefore[0][48][:],
		t.TrieProofsReceiverBefore[0][49][:],
		t.TrieProofsReceiverBefore[0][50][:],
		t.TrieProofsReceiverBefore[0][51][:],
		t.TrieProofsReceiverBefore[0][52][:],
		t.TrieProofsReceiverBefore[0][53][:],
		t.TrieProofsReceiverBefore[0][54][:],
		t.TrieProofsReceiverBefore[0][55][:],
		t.TrieProofsReceiverBefore[0][56][:],
		t.TrieProofsReceiverBefore[0][57][:],
		t.TrieProofsReceiverBefore[0][58][:],
		t.TrieProofsReceiverBefore[0][59][:],
		t.TrieProofsReceiverBefore[0][60][:],
		t.TrieProofsReceiverBefore[0][61][:],
		t.TrieProofsReceiverBefore[0][62][:],
		t.TrieProofsReceiverBefore[0][63][:],
		t.TrieProofsReceiverBefore[0][64][:],
		t.TrieProofsReceiverBefore[0][65][:],
		t.TrieProofsReceiverBefore[0][66][:],
		t.TrieProofsReceiverBefore[0][67][:],
		t.TrieProofsReceiverBefore[0][68][:],
		t.TrieProofsReceiverBefore[0][69][:],
		t.TrieProofsReceiverBefore[0][70][:],
		t.TrieProofsReceiverBefore[0][71][:],
		t.TrieProofsReceiverBefore[0][72][:],
		t.TrieProofsReceiverBefore[0][73][:],
		t.TrieProofsReceiverBefore[0][74][:],
		t.TrieProofsReceiverBefore[0][75][:],
		t.TrieProofsReceiverBefore[0][76][:],
		t.TrieProofsReceiverBefore[0][77][:],
		t.TrieProofsReceiverBefore[0][78][:],
		t.TrieProofsReceiverBefore[0][79][:],
		t.TrieProofsReceiverBefore[0][80][:],
		t.TrieProofsReceiverBefore[0][81][:],
		t.TrieProofsReceiverBefore[0][82][:],
		t.TrieProofsReceiverBefore[0][83][:],
		t.TrieProofsReceiverBefore[0][84][:],
		t.TrieProofsReceiverBefore[0][85][:],
		t.TrieProofsReceiverBefore[0][86][:],
		t.TrieProofsReceiverBefore[0][87][:],
		t.TrieProofsReceiverBefore[0][88][:],
		t.TrieProofsReceiverBefore[0][89][:],
		t.TrieProofsReceiverBefore[0][90][:],
		t.TrieProofsReceiverBefore[0][91][:],
		t.TrieProofsReceiverBefore[0][92][:],
		t.TrieProofsReceiverBefore[0][93][:],
		t.TrieProofsReceiverBefore[0][94][:],
		t.TrieProofsReceiverBefore[0][95][:],
		t.TrieProofsReceiverBefore[0][96][:],
		t.TrieProofsReceiverBefore[0][97][:],
		t.TrieProofsReceiverBefore[0][98][:],
		t.TrieProofsReceiverBefore[0][99][:],
		t.TrieProofsReceiverBefore[0][100][:],
		t.TrieProofsReceiverBefore[0][101][:],
		t.TrieProofsReceiverBefore[0][102][:],
		t.TrieProofsReceiverBefore[0][103][:],
		t.TrieProofsReceiverBefore[0][104][:],
		t.TrieProofsReceiverBefore[0][105][:],
		t.TrieProofsReceiverBefore[0][106][:],
		t.TrieProofsReceiverBefore[0][107][:],
		t.TrieProofsReceiverBefore[0][108][:],
		t.TrieProofsReceiverBefore[0][109][:],
		t.TrieProofsReceiverBefore[0][110][:],
		t.TrieProofsReceiverBefore[0][111][:],
		t.TrieProofsReceiverBefore[0][112][:],
		t.TrieProofsReceiverBefore[0][113][:],
		t.TrieProofsReceiverBefore[0][114][:],
		t.TrieProofsReceiverBefore[0][115][:],
		t.TrieProofsReceiverBefore[0][116][:],
		t.TrieProofsReceiverBefore[0][117][:],
		t.TrieProofsReceiverBefore[0][118][:],
		t.TrieProofsReceiverBefore[0][119][:],
		t.TrieProofsReceiverBefore[0][120][:],
		t.TrieProofsReceiverBefore[0][121][:],
		t.TrieProofsReceiverBefore[0][122][:],
		t.TrieProofsReceiverBefore[0][123][:],
		t.TrieProofsReceiverBefore[0][124][:],
		t.TrieProofsReceiverBefore[0][125][:],
		t.TrieProofsReceiverBefore[0][126][:],
		t.TrieProofsReceiverBefore[0][127][:],
		t.TrieProofsReceiverBefore[0][128][:],
		t.TrieProofsReceiverBefore[0][129][:],
		t.TrieProofsReceiverBefore[0][130][:],
		t.TrieProofsReceiverBefore[0][131][:],
		t.TrieProofsReceiverBefore[0][132][:],
		t.TrieProofsReceiverBefore[0][133][:],
		t.TrieProofsReceiverBefore[0][134][:],
		t.TrieProofsReceiverBefore[0][135][:],
		t.TrieProofsReceiverBefore[0][136][:],
		t.TrieProofsReceiverBefore[0][137][:],
		t.TrieProofsReceiverBefore[0][138][:],
		t.TrieProofsReceiverBefore[0][139][:],
		t.TrieProofsReceiverBefore[0][140][:],
		t.TrieProofsReceiverBefore[0][141][:],
		t.TrieProofsReceiverBefore[0][142][:],
		t.TrieProofsReceiverBefore[0][143][:],
		t.TrieProofsReceiverBefore[0][144][:],
		t.TrieProofsReceiverBefore[0][145][:],
		t.TrieProofsReceiverBefore[0][146][:],
		t.TrieProofsReceiverBefore[0][147][:],
		t.TrieProofsReceiverBefore[0][148][:],
		t.TrieProofsReceiverBefore[0][149][:],
		t.TrieProofsReceiverBefore[0][150][:],
		t.TrieProofsReceiverBefore[0][151][:],
		t.TrieProofsReceiverBefore[0][152][:],
		t.TrieProofsReceiverBefore[0][153][:],
		t.TrieProofsReceiverBefore[0][154][:],
		t.TrieProofsReceiverBefore[0][155][:],
		t.TrieProofsReceiverBefore[0][156][:],
		t.TrieProofsReceiverBefore[0][157][:],
		t.TrieProofsReceiverBefore[0][158][:],
		t.TrieProofsReceiverBefore[0][159][:],
		t.TrieProofsReceiverBefore[0][160][:],
		t.TrieProofsReceiverBefore[0][161][:],
		t.TrieProofsReceiverBefore[0][162][:],
		t.TrieProofsReceiverBefore[0][163][:],
		t.TrieProofsReceiverBefore[0][164][:],
		t.TrieProofsReceiverBefore[0][165][:],
		t.TrieProofsReceiverBefore[0][166][:],
		t.TrieProofsReceiverBefore[0][167][:],
		t.TrieProofsReceiverBefore[0][168][:],
		t.TrieProofsReceiverBefore[0][169][:],
		t.TrieProofsReceiverBefore[0][170][:],
		t.TrieProofsReceiverBefore[0][171][:],
		t.TrieProofsReceiverBefore[0][172][:],
		t.TrieProofsReceiverBefore[0][173][:],
		t.TrieProofsReceiverBefore[0][174][:],
		t.TrieProofsReceiverBefore[0][175][:],
		t.TrieProofsReceiverBefore[0][176][:],
		t.TrieProofsReceiverBefore[0][177][:],
		t.TrieProofsReceiverBefore[0][178][:],
		t.TrieProofsReceiverBefore[0][179][:],
		t.TrieProofsReceiverBefore[0][180][:],
		t.TrieProofsReceiverBefore[0][181][:],
		t.TrieProofsReceiverBefore[0][182][:],
		t.TrieProofsReceiverBefore[0][183][:],
		t.TrieProofsReceiverBefore[0][184][:],
		t.TrieProofsReceiverBefore[0][185][:],
		t.TrieProofsReceiverBefore[0][186][:],
		t.TrieProofsReceiverBefore[0][187][:],
		t.TrieProofsReceiverBefore[0][188][:],
		t.TrieProofsReceiverBefore[0][189][:],
		t.TrieProofsReceiverBefore[0][190][:],
		t.TrieProofsReceiverBefore[0][191][:],
		t.TrieProofsReceiverBefore[0][192][:],
		t.TrieProofsReceiverBefore[0][193][:],
		t.TrieProofsReceiverBefore[0][194][:],
		t.TrieProofsReceiverBefore[0][195][:],
		t.TrieProofsReceiverBefore[0][196][:],
		t.TrieProofsReceiverBefore[0][197][:],
		t.TrieProofsReceiverBefore[0][198][:],
		t.TrieProofsReceiverBefore[0][199][:],
		t.TrieProofsReceiverBefore[0][200][:],
		t.TrieProofsReceiverBefore[0][201][:],
		t.TrieProofsReceiverBefore[0][202][:],
		t.TrieProofsReceiverBefore[0][203][:],
		t.TrieProofsReceiverBefore[0][204][:],
		t.TrieProofsReceiverBefore[0][205][:],
		t.TrieProofsReceiverBefore[0][206][:],
		t.TrieProofsReceiverBefore[0][207][:],
		t.TrieProofsReceiverBefore[0][208][:],
		t.TrieProofsReceiverBefore[0][209][:],
		t.TrieProofsReceiverBefore[0][210][:],
		t.TrieProofsReceiverBefore[0][211][:],
		t.TrieProofsReceiverBefore[0][212][:],
		t.TrieProofsReceiverBefore[0][213][:],
		t.TrieProofsReceiverBefore[0][214][:],
		t.TrieProofsReceiverBefore[0][215][:],
		t.TrieProofsReceiverBefore[0][216][:],
		t.TrieProofsReceiverBefore[0][217][:],
		t.TrieProofsReceiverBefore[0][218][:],
		t.TrieProofsReceiverBefore[0][219][:],
		t.TrieProofsReceiverBefore[0][220][:],
		t.TrieProofsReceiverBefore[0][221][:],
		t.TrieProofsReceiverBefore[0][222][:],
		t.TrieProofsReceiverBefore[0][223][:],
		t.TrieProofsReceiverBefore[0][224][:],
		t.TrieProofsReceiverBefore[0][225][:],
		t.TrieProofsReceiverBefore[0][226][:],
		t.TrieProofsReceiverBefore[0][227][:],
		t.TrieProofsReceiverBefore[0][228][:],
		t.TrieProofsReceiverBefore[0][229][:],
		t.TrieProofsReceiverBefore[0][230][:],
		t.TrieProofsReceiverBefore[0][231][:],
		t.TrieProofsReceiverBefore[0][232][:],
		t.TrieProofsReceiverBefore[0][233][:],
		t.TrieProofsReceiverBefore[0][234][:],
		t.TrieProofsReceiverBefore[0][235][:],
		t.TrieProofsReceiverBefore[0][236][:],
		t.TrieProofsReceiverBefore[0][237][:],
		t.TrieProofsReceiverBefore[0][238][:],
		t.TrieProofsReceiverBefore[0][239][:],
		t.TrieProofsReceiverBefore[0][240][:],
		t.TrieProofsReceiverBefore[0][241][:],
		t.TrieProofsReceiverBefore[0][242][:],
		t.TrieProofsReceiverBefore[0][243][:],
		t.TrieProofsReceiverBefore[0][244][:],
		t.TrieProofsReceiverBefore[0][245][:],
		t.TrieProofsReceiverBefore[0][246][:],
		t.TrieProofsReceiverBefore[0][247][:],
		t.TrieProofsReceiverBefore[0][248][:],
		t.TrieProofsReceiverBefore[0][249][:],
		t.TrieProofsReceiverBefore[0][250][:],
		t.TrieProofsReceiverBefore[0][251][:],
		t.TrieProofsReceiverBefore[0][252][:],
		t.TrieProofsReceiverBefore[0][253][:],
		t.TrieProofsReceiverBefore[0][254][:],
		t.TrieProofsReceiverBefore[0][255][:],
		t.TrieProofsReceiverBefore[0][256][:],
		t.TrieProofsReceiverBefore[0][257][:],
		t.TriePathReceiverBefore[0][:])

	trie_mimc.Validate256(api, hashFunc, t.TrieRootHashesAfter[0],
		t.TrieProofsSenderAfter[0][0][:],
		t.TrieProofsSenderAfter[0][1][:],
		t.TrieProofsSenderAfter[0][2][:],
		t.TrieProofsSenderAfter[0][3][:],
		t.TrieProofsSenderAfter[0][4][:],
		t.TrieProofsSenderAfter[0][5][:],
		t.TrieProofsSenderAfter[0][6][:],
		t.TrieProofsSenderAfter[0][7][:],
		t.TrieProofsSenderAfter[0][8][:],
		t.TrieProofsSenderAfter[0][9][:],
		t.TrieProofsSenderAfter[0][10][:],
		t.TrieProofsSenderAfter[0][11][:],
		t.TrieProofsSenderAfter[0][12][:],
		t.TrieProofsSenderAfter[0][13][:],
		t.TrieProofsSenderAfter[0][14][:],
		t.TrieProofsSenderAfter[0][15][:],
		t.TrieProofsSenderAfter[0][16][:],
		t.TrieProofsSenderAfter[0][17][:],
		t.TrieProofsSenderAfter[0][18][:],
		t.TrieProofsSenderAfter[0][19][:],
		t.TrieProofsSenderAfter[0][20][:],
		t.TrieProofsSenderAfter[0][21][:],
		t.TrieProofsSenderAfter[0][22][:],
		t.TrieProofsSenderAfter[0][23][:],
		t.TrieProofsSenderAfter[0][24][:],
		t.TrieProofsSenderAfter[0][25][:],
		t.TrieProofsSenderAfter[0][26][:],
		t.TrieProofsSenderAfter[0][27][:],
		t.TrieProofsSenderAfter[0][28][:],
		t.TrieProofsSenderAfter[0][29][:],
		t.TrieProofsSenderAfter[0][30][:],
		t.TrieProofsSenderAfter[0][31][:],
		t.TrieProofsSenderAfter[0][32][:],
		t.TrieProofsSenderAfter[0][33][:],
		t.TrieProofsSenderAfter[0][34][:],
		t.TrieProofsSenderAfter[0][35][:],
		t.TrieProofsSenderAfter[0][36][:],
		t.TrieProofsSenderAfter[0][37][:],
		t.TrieProofsSenderAfter[0][38][:],
		t.TrieProofsSenderAfter[0][39][:],
		t.TrieProofsSenderAfter[0][40][:],
		t.TrieProofsSenderAfter[0][41][:],
		t.TrieProofsSenderAfter[0][42][:],
		t.TrieProofsSenderAfter[0][43][:],
		t.TrieProofsSenderAfter[0][44][:],
		t.TrieProofsSenderAfter[0][45][:],
		t.TrieProofsSenderAfter[0][46][:],
		t.TrieProofsSenderAfter[0][47][:],
		t.TrieProofsSenderAfter[0][48][:],
		t.TrieProofsSenderAfter[0][49][:],
		t.TrieProofsSenderAfter[0][50][:],
		t.TrieProofsSenderAfter[0][51][:],
		t.TrieProofsSenderAfter[0][52][:],
		t.TrieProofsSenderAfter[0][53][:],
		t.TrieProofsSenderAfter[0][54][:],
		t.TrieProofsSenderAfter[0][55][:],
		t.TrieProofsSenderAfter[0][56][:],
		t.TrieProofsSenderAfter[0][57][:],
		t.TrieProofsSenderAfter[0][58][:],
		t.TrieProofsSenderAfter[0][59][:],
		t.TrieProofsSenderAfter[0][60][:],
		t.TrieProofsSenderAfter[0][61][:],
		t.TrieProofsSenderAfter[0][62][:],
		t.TrieProofsSenderAfter[0][63][:],
		t.TrieProofsSenderAfter[0][64][:],
		t.TrieProofsSenderAfter[0][65][:],
		t.TrieProofsSenderAfter[0][66][:],
		t.TrieProofsSenderAfter[0][67][:],
		t.TrieProofsSenderAfter[0][68][:],
		t.TrieProofsSenderAfter[0][69][:],
		t.TrieProofsSenderAfter[0][70][:],
		t.TrieProofsSenderAfter[0][71][:],
		t.TrieProofsSenderAfter[0][72][:],
		t.TrieProofsSenderAfter[0][73][:],
		t.TrieProofsSenderAfter[0][74][:],
		t.TrieProofsSenderAfter[0][75][:],
		t.TrieProofsSenderAfter[0][76][:],
		t.TrieProofsSenderAfter[0][77][:],
		t.TrieProofsSenderAfter[0][78][:],
		t.TrieProofsSenderAfter[0][79][:],
		t.TrieProofsSenderAfter[0][80][:],
		t.TrieProofsSenderAfter[0][81][:],
		t.TrieProofsSenderAfter[0][82][:],
		t.TrieProofsSenderAfter[0][83][:],
		t.TrieProofsSenderAfter[0][84][:],
		t.TrieProofsSenderAfter[0][85][:],
		t.TrieProofsSenderAfter[0][86][:],
		t.TrieProofsSenderAfter[0][87][:],
		t.TrieProofsSenderAfter[0][88][:],
		t.TrieProofsSenderAfter[0][89][:],
		t.TrieProofsSenderAfter[0][90][:],
		t.TrieProofsSenderAfter[0][91][:],
		t.TrieProofsSenderAfter[0][92][:],
		t.TrieProofsSenderAfter[0][93][:],
		t.TrieProofsSenderAfter[0][94][:],
		t.TrieProofsSenderAfter[0][95][:],
		t.TrieProofsSenderAfter[0][96][:],
		t.TrieProofsSenderAfter[0][97][:],
		t.TrieProofsSenderAfter[0][98][:],
		t.TrieProofsSenderAfter[0][99][:],
		t.TrieProofsSenderAfter[0][100][:],
		t.TrieProofsSenderAfter[0][101][:],
		t.TrieProofsSenderAfter[0][102][:],
		t.TrieProofsSenderAfter[0][103][:],
		t.TrieProofsSenderAfter[0][104][:],
		t.TrieProofsSenderAfter[0][105][:],
		t.TrieProofsSenderAfter[0][106][:],
		t.TrieProofsSenderAfter[0][107][:],
		t.TrieProofsSenderAfter[0][108][:],
		t.TrieProofsSenderAfter[0][109][:],
		t.TrieProofsSenderAfter[0][110][:],
		t.TrieProofsSenderAfter[0][111][:],
		t.TrieProofsSenderAfter[0][112][:],
		t.TrieProofsSenderAfter[0][113][:],
		t.TrieProofsSenderAfter[0][114][:],
		t.TrieProofsSenderAfter[0][115][:],
		t.TrieProofsSenderAfter[0][116][:],
		t.TrieProofsSenderAfter[0][117][:],
		t.TrieProofsSenderAfter[0][118][:],
		t.TrieProofsSenderAfter[0][119][:],
		t.TrieProofsSenderAfter[0][120][:],
		t.TrieProofsSenderAfter[0][121][:],
		t.TrieProofsSenderAfter[0][122][:],
		t.TrieProofsSenderAfter[0][123][:],
		t.TrieProofsSenderAfter[0][124][:],
		t.TrieProofsSenderAfter[0][125][:],
		t.TrieProofsSenderAfter[0][126][:],
		t.TrieProofsSenderAfter[0][127][:],
		t.TrieProofsSenderAfter[0][128][:],
		t.TrieProofsSenderAfter[0][129][:],
		t.TrieProofsSenderAfter[0][130][:],
		t.TrieProofsSenderAfter[0][131][:],
		t.TrieProofsSenderAfter[0][132][:],
		t.TrieProofsSenderAfter[0][133][:],
		t.TrieProofsSenderAfter[0][134][:],
		t.TrieProofsSenderAfter[0][135][:],
		t.TrieProofsSenderAfter[0][136][:],
		t.TrieProofsSenderAfter[0][137][:],
		t.TrieProofsSenderAfter[0][138][:],
		t.TrieProofsSenderAfter[0][139][:],
		t.TrieProofsSenderAfter[0][140][:],
		t.TrieProofsSenderAfter[0][141][:],
		t.TrieProofsSenderAfter[0][142][:],
		t.TrieProofsSenderAfter[0][143][:],
		t.TrieProofsSenderAfter[0][144][:],
		t.TrieProofsSenderAfter[0][145][:],
		t.TrieProofsSenderAfter[0][146][:],
		t.TrieProofsSenderAfter[0][147][:],
		t.TrieProofsSenderAfter[0][148][:],
		t.TrieProofsSenderAfter[0][149][:],
		t.TrieProofsSenderAfter[0][150][:],
		t.TrieProofsSenderAfter[0][151][:],
		t.TrieProofsSenderAfter[0][152][:],
		t.TrieProofsSenderAfter[0][153][:],
		t.TrieProofsSenderAfter[0][154][:],
		t.TrieProofsSenderAfter[0][155][:],
		t.TrieProofsSenderAfter[0][156][:],
		t.TrieProofsSenderAfter[0][157][:],
		t.TrieProofsSenderAfter[0][158][:],
		t.TrieProofsSenderAfter[0][159][:],
		t.TrieProofsSenderAfter[0][160][:],
		t.TrieProofsSenderAfter[0][161][:],
		t.TrieProofsSenderAfter[0][162][:],
		t.TrieProofsSenderAfter[0][163][:],
		t.TrieProofsSenderAfter[0][164][:],
		t.TrieProofsSenderAfter[0][165][:],
		t.TrieProofsSenderAfter[0][166][:],
		t.TrieProofsSenderAfter[0][167][:],
		t.TrieProofsSenderAfter[0][168][:],
		t.TrieProofsSenderAfter[0][169][:],
		t.TrieProofsSenderAfter[0][170][:],
		t.TrieProofsSenderAfter[0][171][:],
		t.TrieProofsSenderAfter[0][172][:],
		t.TrieProofsSenderAfter[0][173][:],
		t.TrieProofsSenderAfter[0][174][:],
		t.TrieProofsSenderAfter[0][175][:],
		t.TrieProofsSenderAfter[0][176][:],
		t.TrieProofsSenderAfter[0][177][:],
		t.TrieProofsSenderAfter[0][178][:],
		t.TrieProofsSenderAfter[0][179][:],
		t.TrieProofsSenderAfter[0][180][:],
		t.TrieProofsSenderAfter[0][181][:],
		t.TrieProofsSenderAfter[0][182][:],
		t.TrieProofsSenderAfter[0][183][:],
		t.TrieProofsSenderAfter[0][184][:],
		t.TrieProofsSenderAfter[0][185][:],
		t.TrieProofsSenderAfter[0][186][:],
		t.TrieProofsSenderAfter[0][187][:],
		t.TrieProofsSenderAfter[0][188][:],
		t.TrieProofsSenderAfter[0][189][:],
		t.TrieProofsSenderAfter[0][190][:],
		t.TrieProofsSenderAfter[0][191][:],
		t.TrieProofsSenderAfter[0][192][:],
		t.TrieProofsSenderAfter[0][193][:],
		t.TrieProofsSenderAfter[0][194][:],
		t.TrieProofsSenderAfter[0][195][:],
		t.TrieProofsSenderAfter[0][196][:],
		t.TrieProofsSenderAfter[0][197][:],
		t.TrieProofsSenderAfter[0][198][:],
		t.TrieProofsSenderAfter[0][199][:],
		t.TrieProofsSenderAfter[0][200][:],
		t.TrieProofsSenderAfter[0][201][:],
		t.TrieProofsSenderAfter[0][202][:],
		t.TrieProofsSenderAfter[0][203][:],
		t.TrieProofsSenderAfter[0][204][:],
		t.TrieProofsSenderAfter[0][205][:],
		t.TrieProofsSenderAfter[0][206][:],
		t.TrieProofsSenderAfter[0][207][:],
		t.TrieProofsSenderAfter[0][208][:],
		t.TrieProofsSenderAfter[0][209][:],
		t.TrieProofsSenderAfter[0][210][:],
		t.TrieProofsSenderAfter[0][211][:],
		t.TrieProofsSenderAfter[0][212][:],
		t.TrieProofsSenderAfter[0][213][:],
		t.TrieProofsSenderAfter[0][214][:],
		t.TrieProofsSenderAfter[0][215][:],
		t.TrieProofsSenderAfter[0][216][:],
		t.TrieProofsSenderAfter[0][217][:],
		t.TrieProofsSenderAfter[0][218][:],
		t.TrieProofsSenderAfter[0][219][:],
		t.TrieProofsSenderAfter[0][220][:],
		t.TrieProofsSenderAfter[0][221][:],
		t.TrieProofsSenderAfter[0][222][:],
		t.TrieProofsSenderAfter[0][223][:],
		t.TrieProofsSenderAfter[0][224][:],
		t.TrieProofsSenderAfter[0][225][:],
		t.TrieProofsSenderAfter[0][226][:],
		t.TrieProofsSenderAfter[0][227][:],
		t.TrieProofsSenderAfter[0][228][:],
		t.TrieProofsSenderAfter[0][229][:],
		t.TrieProofsSenderAfter[0][230][:],
		t.TrieProofsSenderAfter[0][231][:],
		t.TrieProofsSenderAfter[0][232][:],
		t.TrieProofsSenderAfter[0][233][:],
		t.TrieProofsSenderAfter[0][234][:],
		t.TrieProofsSenderAfter[0][235][:],
		t.TrieProofsSenderAfter[0][236][:],
		t.TrieProofsSenderAfter[0][237][:],
		t.TrieProofsSenderAfter[0][238][:],
		t.TrieProofsSenderAfter[0][239][:],
		t.TrieProofsSenderAfter[0][240][:],
		t.TrieProofsSenderAfter[0][241][:],
		t.TrieProofsSenderAfter[0][242][:],
		t.TrieProofsSenderAfter[0][243][:],
		t.TrieProofsSenderAfter[0][244][:],
		t.TrieProofsSenderAfter[0][245][:],
		t.TrieProofsSenderAfter[0][246][:],
		t.TrieProofsSenderAfter[0][247][:],
		t.TrieProofsSenderAfter[0][248][:],
		t.TrieProofsSenderAfter[0][249][:],
		t.TrieProofsSenderAfter[0][250][:],
		t.TrieProofsSenderAfter[0][251][:],
		t.TrieProofsSenderAfter[0][252][:],
		t.TrieProofsSenderAfter[0][253][:],
		t.TrieProofsSenderAfter[0][254][:],
		t.TrieProofsSenderAfter[0][255][:],
		t.TrieProofsSenderAfter[0][256][:],
		t.TrieProofsSenderAfter[0][257][:],
		t.TriePathSenderAfter[0][:])
	trie_mimc.Validate256(api, hashFunc, t.TrieRootHashesAfter[0],
		t.TrieProofsReceiverAfter[0][0][:],
		t.TrieProofsReceiverAfter[0][1][:],
		t.TrieProofsReceiverAfter[0][2][:],
		t.TrieProofsReceiverAfter[0][3][:],
		t.TrieProofsReceiverAfter[0][4][:],
		t.TrieProofsReceiverAfter[0][5][:],
		t.TrieProofsReceiverAfter[0][6][:],
		t.TrieProofsReceiverAfter[0][7][:],
		t.TrieProofsReceiverAfter[0][8][:],
		t.TrieProofsReceiverAfter[0][9][:],
		t.TrieProofsReceiverAfter[0][10][:],
		t.TrieProofsReceiverAfter[0][11][:],
		t.TrieProofsReceiverAfter[0][12][:],
		t.TrieProofsReceiverAfter[0][13][:],
		t.TrieProofsReceiverAfter[0][14][:],
		t.TrieProofsReceiverAfter[0][15][:],
		t.TrieProofsReceiverAfter[0][16][:],
		t.TrieProofsReceiverAfter[0][17][:],
		t.TrieProofsReceiverAfter[0][18][:],
		t.TrieProofsReceiverAfter[0][19][:],
		t.TrieProofsReceiverAfter[0][20][:],
		t.TrieProofsReceiverAfter[0][21][:],
		t.TrieProofsReceiverAfter[0][22][:],
		t.TrieProofsReceiverAfter[0][23][:],
		t.TrieProofsReceiverAfter[0][24][:],
		t.TrieProofsReceiverAfter[0][25][:],
		t.TrieProofsReceiverAfter[0][26][:],
		t.TrieProofsReceiverAfter[0][27][:],
		t.TrieProofsReceiverAfter[0][28][:],
		t.TrieProofsReceiverAfter[0][29][:],
		t.TrieProofsReceiverAfter[0][30][:],
		t.TrieProofsReceiverAfter[0][31][:],
		t.TrieProofsReceiverAfter[0][32][:],
		t.TrieProofsReceiverAfter[0][33][:],
		t.TrieProofsReceiverAfter[0][34][:],
		t.TrieProofsReceiverAfter[0][35][:],
		t.TrieProofsReceiverAfter[0][36][:],
		t.TrieProofsReceiverAfter[0][37][:],
		t.TrieProofsReceiverAfter[0][38][:],
		t.TrieProofsReceiverAfter[0][39][:],
		t.TrieProofsReceiverAfter[0][40][:],
		t.TrieProofsReceiverAfter[0][41][:],
		t.TrieProofsReceiverAfter[0][42][:],
		t.TrieProofsReceiverAfter[0][43][:],
		t.TrieProofsReceiverAfter[0][44][:],
		t.TrieProofsReceiverAfter[0][45][:],
		t.TrieProofsReceiverAfter[0][46][:],
		t.TrieProofsReceiverAfter[0][47][:],
		t.TrieProofsReceiverAfter[0][48][:],
		t.TrieProofsReceiverAfter[0][49][:],
		t.TrieProofsReceiverAfter[0][50][:],
		t.TrieProofsReceiverAfter[0][51][:],
		t.TrieProofsReceiverAfter[0][52][:],
		t.TrieProofsReceiverAfter[0][53][:],
		t.TrieProofsReceiverAfter[0][54][:],
		t.TrieProofsReceiverAfter[0][55][:],
		t.TrieProofsReceiverAfter[0][56][:],
		t.TrieProofsReceiverAfter[0][57][:],
		t.TrieProofsReceiverAfter[0][58][:],
		t.TrieProofsReceiverAfter[0][59][:],
		t.TrieProofsReceiverAfter[0][60][:],
		t.TrieProofsReceiverAfter[0][61][:],
		t.TrieProofsReceiverAfter[0][62][:],
		t.TrieProofsReceiverAfter[0][63][:],
		t.TrieProofsReceiverAfter[0][64][:],
		t.TrieProofsReceiverAfter[0][65][:],
		t.TrieProofsReceiverAfter[0][66][:],
		t.TrieProofsReceiverAfter[0][67][:],
		t.TrieProofsReceiverAfter[0][68][:],
		t.TrieProofsReceiverAfter[0][69][:],
		t.TrieProofsReceiverAfter[0][70][:],
		t.TrieProofsReceiverAfter[0][71][:],
		t.TrieProofsReceiverAfter[0][72][:],
		t.TrieProofsReceiverAfter[0][73][:],
		t.TrieProofsReceiverAfter[0][74][:],
		t.TrieProofsReceiverAfter[0][75][:],
		t.TrieProofsReceiverAfter[0][76][:],
		t.TrieProofsReceiverAfter[0][77][:],
		t.TrieProofsReceiverAfter[0][78][:],
		t.TrieProofsReceiverAfter[0][79][:],
		t.TrieProofsReceiverAfter[0][80][:],
		t.TrieProofsReceiverAfter[0][81][:],
		t.TrieProofsReceiverAfter[0][82][:],
		t.TrieProofsReceiverAfter[0][83][:],
		t.TrieProofsReceiverAfter[0][84][:],
		t.TrieProofsReceiverAfter[0][85][:],
		t.TrieProofsReceiverAfter[0][86][:],
		t.TrieProofsReceiverAfter[0][87][:],
		t.TrieProofsReceiverAfter[0][88][:],
		t.TrieProofsReceiverAfter[0][89][:],
		t.TrieProofsReceiverAfter[0][90][:],
		t.TrieProofsReceiverAfter[0][91][:],
		t.TrieProofsReceiverAfter[0][92][:],
		t.TrieProofsReceiverAfter[0][93][:],
		t.TrieProofsReceiverAfter[0][94][:],
		t.TrieProofsReceiverAfter[0][95][:],
		t.TrieProofsReceiverAfter[0][96][:],
		t.TrieProofsReceiverAfter[0][97][:],
		t.TrieProofsReceiverAfter[0][98][:],
		t.TrieProofsReceiverAfter[0][99][:],
		t.TrieProofsReceiverAfter[0][100][:],
		t.TrieProofsReceiverAfter[0][101][:],
		t.TrieProofsReceiverAfter[0][102][:],
		t.TrieProofsReceiverAfter[0][103][:],
		t.TrieProofsReceiverAfter[0][104][:],
		t.TrieProofsReceiverAfter[0][105][:],
		t.TrieProofsReceiverAfter[0][106][:],
		t.TrieProofsReceiverAfter[0][107][:],
		t.TrieProofsReceiverAfter[0][108][:],
		t.TrieProofsReceiverAfter[0][109][:],
		t.TrieProofsReceiverAfter[0][110][:],
		t.TrieProofsReceiverAfter[0][111][:],
		t.TrieProofsReceiverAfter[0][112][:],
		t.TrieProofsReceiverAfter[0][113][:],
		t.TrieProofsReceiverAfter[0][114][:],
		t.TrieProofsReceiverAfter[0][115][:],
		t.TrieProofsReceiverAfter[0][116][:],
		t.TrieProofsReceiverAfter[0][117][:],
		t.TrieProofsReceiverAfter[0][118][:],
		t.TrieProofsReceiverAfter[0][119][:],
		t.TrieProofsReceiverAfter[0][120][:],
		t.TrieProofsReceiverAfter[0][121][:],
		t.TrieProofsReceiverAfter[0][122][:],
		t.TrieProofsReceiverAfter[0][123][:],
		t.TrieProofsReceiverAfter[0][124][:],
		t.TrieProofsReceiverAfter[0][125][:],
		t.TrieProofsReceiverAfter[0][126][:],
		t.TrieProofsReceiverAfter[0][127][:],
		t.TrieProofsReceiverAfter[0][128][:],
		t.TrieProofsReceiverAfter[0][129][:],
		t.TrieProofsReceiverAfter[0][130][:],
		t.TrieProofsReceiverAfter[0][131][:],
		t.TrieProofsReceiverAfter[0][132][:],
		t.TrieProofsReceiverAfter[0][133][:],
		t.TrieProofsReceiverAfter[0][134][:],
		t.TrieProofsReceiverAfter[0][135][:],
		t.TrieProofsReceiverAfter[0][136][:],
		t.TrieProofsReceiverAfter[0][137][:],
		t.TrieProofsReceiverAfter[0][138][:],
		t.TrieProofsReceiverAfter[0][139][:],
		t.TrieProofsReceiverAfter[0][140][:],
		t.TrieProofsReceiverAfter[0][141][:],
		t.TrieProofsReceiverAfter[0][142][:],
		t.TrieProofsReceiverAfter[0][143][:],
		t.TrieProofsReceiverAfter[0][144][:],
		t.TrieProofsReceiverAfter[0][145][:],
		t.TrieProofsReceiverAfter[0][146][:],
		t.TrieProofsReceiverAfter[0][147][:],
		t.TrieProofsReceiverAfter[0][148][:],
		t.TrieProofsReceiverAfter[0][149][:],
		t.TrieProofsReceiverAfter[0][150][:],
		t.TrieProofsReceiverAfter[0][151][:],
		t.TrieProofsReceiverAfter[0][152][:],
		t.TrieProofsReceiverAfter[0][153][:],
		t.TrieProofsReceiverAfter[0][154][:],
		t.TrieProofsReceiverAfter[0][155][:],
		t.TrieProofsReceiverAfter[0][156][:],
		t.TrieProofsReceiverAfter[0][157][:],
		t.TrieProofsReceiverAfter[0][158][:],
		t.TrieProofsReceiverAfter[0][159][:],
		t.TrieProofsReceiverAfter[0][160][:],
		t.TrieProofsReceiverAfter[0][161][:],
		t.TrieProofsReceiverAfter[0][162][:],
		t.TrieProofsReceiverAfter[0][163][:],
		t.TrieProofsReceiverAfter[0][164][:],
		t.TrieProofsReceiverAfter[0][165][:],
		t.TrieProofsReceiverAfter[0][166][:],
		t.TrieProofsReceiverAfter[0][167][:],
		t.TrieProofsReceiverAfter[0][168][:],
		t.TrieProofsReceiverAfter[0][169][:],
		t.TrieProofsReceiverAfter[0][170][:],
		t.TrieProofsReceiverAfter[0][171][:],
		t.TrieProofsReceiverAfter[0][172][:],
		t.TrieProofsReceiverAfter[0][173][:],
		t.TrieProofsReceiverAfter[0][174][:],
		t.TrieProofsReceiverAfter[0][175][:],
		t.TrieProofsReceiverAfter[0][176][:],
		t.TrieProofsReceiverAfter[0][177][:],
		t.TrieProofsReceiverAfter[0][178][:],
		t.TrieProofsReceiverAfter[0][179][:],
		t.TrieProofsReceiverAfter[0][180][:],
		t.TrieProofsReceiverAfter[0][181][:],
		t.TrieProofsReceiverAfter[0][182][:],
		t.TrieProofsReceiverAfter[0][183][:],
		t.TrieProofsReceiverAfter[0][184][:],
		t.TrieProofsReceiverAfter[0][185][:],
		t.TrieProofsReceiverAfter[0][186][:],
		t.TrieProofsReceiverAfter[0][187][:],
		t.TrieProofsReceiverAfter[0][188][:],
		t.TrieProofsReceiverAfter[0][189][:],
		t.TrieProofsReceiverAfter[0][190][:],
		t.TrieProofsReceiverAfter[0][191][:],
		t.TrieProofsReceiverAfter[0][192][:],
		t.TrieProofsReceiverAfter[0][193][:],
		t.TrieProofsReceiverAfter[0][194][:],
		t.TrieProofsReceiverAfter[0][195][:],
		t.TrieProofsReceiverAfter[0][196][:],
		t.TrieProofsReceiverAfter[0][197][:],
		t.TrieProofsReceiverAfter[0][198][:],
		t.TrieProofsReceiverAfter[0][199][:],
		t.TrieProofsReceiverAfter[0][200][:],
		t.TrieProofsReceiverAfter[0][201][:],
		t.TrieProofsReceiverAfter[0][202][:],
		t.TrieProofsReceiverAfter[0][203][:],
		t.TrieProofsReceiverAfter[0][204][:],
		t.TrieProofsReceiverAfter[0][205][:],
		t.TrieProofsReceiverAfter[0][206][:],
		t.TrieProofsReceiverAfter[0][207][:],
		t.TrieProofsReceiverAfter[0][208][:],
		t.TrieProofsReceiverAfter[0][209][:],
		t.TrieProofsReceiverAfter[0][210][:],
		t.TrieProofsReceiverAfter[0][211][:],
		t.TrieProofsReceiverAfter[0][212][:],
		t.TrieProofsReceiverAfter[0][213][:],
		t.TrieProofsReceiverAfter[0][214][:],
		t.TrieProofsReceiverAfter[0][215][:],
		t.TrieProofsReceiverAfter[0][216][:],
		t.TrieProofsReceiverAfter[0][217][:],
		t.TrieProofsReceiverAfter[0][218][:],
		t.TrieProofsReceiverAfter[0][219][:],
		t.TrieProofsReceiverAfter[0][220][:],
		t.TrieProofsReceiverAfter[0][221][:],
		t.TrieProofsReceiverAfter[0][222][:],
		t.TrieProofsReceiverAfter[0][223][:],
		t.TrieProofsReceiverAfter[0][224][:],
		t.TrieProofsReceiverAfter[0][225][:],
		t.TrieProofsReceiverAfter[0][226][:],
		t.TrieProofsReceiverAfter[0][227][:],
		t.TrieProofsReceiverAfter[0][228][:],
		t.TrieProofsReceiverAfter[0][229][:],
		t.TrieProofsReceiverAfter[0][230][:],
		t.TrieProofsReceiverAfter[0][231][:],
		t.TrieProofsReceiverAfter[0][232][:],
		t.TrieProofsReceiverAfter[0][233][:],
		t.TrieProofsReceiverAfter[0][234][:],
		t.TrieProofsReceiverAfter[0][235][:],
		t.TrieProofsReceiverAfter[0][236][:],
		t.TrieProofsReceiverAfter[0][237][:],
		t.TrieProofsReceiverAfter[0][238][:],
		t.TrieProofsReceiverAfter[0][239][:],
		t.TrieProofsReceiverAfter[0][240][:],
		t.TrieProofsReceiverAfter[0][241][:],
		t.TrieProofsReceiverAfter[0][242][:],
		t.TrieProofsReceiverAfter[0][243][:],
		t.TrieProofsReceiverAfter[0][244][:],
		t.TrieProofsReceiverAfter[0][245][:],
		t.TrieProofsReceiverAfter[0][246][:],
		t.TrieProofsReceiverAfter[0][247][:],
		t.TrieProofsReceiverAfter[0][248][:],
		t.TrieProofsReceiverAfter[0][249][:],
		t.TrieProofsReceiverAfter[0][250][:],
		t.TrieProofsReceiverAfter[0][251][:],
		t.TrieProofsReceiverAfter[0][252][:],
		t.TrieProofsReceiverAfter[0][253][:],
		t.TrieProofsReceiverAfter[0][254][:],
		t.TrieProofsReceiverAfter[0][255][:],
		t.TrieProofsReceiverAfter[0][256][:],
		t.TrieProofsReceiverAfter[0][257][:],
		t.TriePathReceiverAfter[0][:])

	return nil
}

func TestCircuitInclusionProof(t *testing.T) {

	if testing.Short() {
		t.Skip("skipping rollup tests for circleCI")
	}

	operator, users := createOperator(nbAccounts)

	// read accounts involved in the transfer
	sender, err := operator.readAccount(0)
	if err != nil {
		t.Fatal(err)
	}

	receiver, err := operator.readAccount(1)
	if err != nil {
		t.Fatal(err)
	}

	// create the transfer and sign it
	amount := uint64(16)
	transfer := NewTransfer(amount, sender.pubKey, receiver.pubKey, sender.nonce)

	// sign the transfer
	_, err = transfer.Sign(users[0], operator.h)
	if err != nil {
		t.Fatal(err)
	}

	// update the state from the received transfer
	err = operator.updateState(transfer, 0)
	if err != nil {
		t.Fatal(err)
	}

	// verifies the proofs of inclusion of the transfer
	assert := test.NewAssert(t)

	var inclusionProofCircuit circuitInclusionProof

	assert.ProverSucceeded(&inclusionProofCircuit, &operator.witnesses, test.WithCurves(ecc.BN254), test.WithCompileOpts(frontend.IgnoreUnconstrainedInputs()))

}

type circuitUpdateAccount Circuit

// Circuit implements part of the rollup circuit only by delcaring a subset of the constraints
func (t *circuitUpdateAccount) Define(api frontend.API) error {
	if err := (*Circuit)(t).postInit(api); err != nil {
		return err
	}
	verifyAccountUpdated(api, t.SenderAccountsBefore[0], t.ReceiverAccountsBefore[0],
		t.SenderAccountsAfter[0], t.ReceiverAccountsAfter[0], t.Transfers[0].Amount)
	return nil
}

func TestCircuitUpdateAccount(t *testing.T) {

	if testing.Short() {
		t.Skip("skipping rollup tests for circleCI")
	}

	operator, users := createOperator(nbAccounts)

	// read accounts involved in the transfer
	sender, err := operator.readAccount(0)
	if err != nil {
		t.Fatal(err)
	}

	receiver, err := operator.readAccount(1)
	if err != nil {
		t.Fatal(err)
	}

	// create the transfer and sign it
	amount := uint64(10)
	transfer := NewTransfer(amount, sender.pubKey, receiver.pubKey, sender.nonce)

	// sign the transfer
	_, err = transfer.Sign(users[0], operator.h)
	if err != nil {
		t.Fatal(err)
	}

	// update the state from the received transfer
	err = operator.updateState(transfer, 0)
	if err != nil {
		t.Fatal(err)
	}

	assert := test.NewAssert(t)

	var updateAccountCircuit circuitUpdateAccount

	assert.ProverSucceeded(&updateAccountCircuit, &operator.witnesses, test.WithCurves(ecc.BN254), test.WithCompileOpts(frontend.IgnoreUnconstrainedInputs()))

}

func TestCircuitFull(t *testing.T) {

	if testing.Short() {
		t.Skip("skipping rollup tests for circleCI")
	}

	operator, users := createOperator(nbAccounts)

	// read accounts involved in the transfer
	sender, err := operator.readAccount(0)
	if err != nil {
		t.Fatal(err)
	}

	receiver, err := operator.readAccount(1)
	if err != nil {
		t.Fatal(err)
	}

	// create the transfer and sign it
	amount := uint64(10)
	transfer := NewTransfer(amount, sender.pubKey, receiver.pubKey, sender.nonce)

	// sign the transfer
	_, err = transfer.Sign(users[0], operator.h)
	if err != nil {
		t.Fatal(err)
	}

	// update the state from the received transfer
	err = operator.updateState(transfer, 0)
	if err != nil {
		t.Fatal(err)
	}

	assert := test.NewAssert(t)
	// verifies the proofs of inclusion of the transfer

	var rollupCircuit Circuit

	// TODO full circuit has some unconstrained inputs, that's odd.
	assert.ProverSucceeded(&rollupCircuit, &operator.witnesses, test.WithCurves(ecc.BN254), test.WithCompileOpts(frontend.IgnoreUnconstrainedInputs()))

}
