/*
Copyright © 2020 ConsenSys

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package rollup

import (
	tedwards "github.com/consensys/gnark-crypto/ecc/twistededwards"
	"github.com/consensys/gnark/frontend"
	"github.com/consensys/gnark/std/algebra/twistededwards"
	"github.com/consensys/gnark/std/hash/mimc"
	"github.com/consensys/gnark/std/signature/eddsa"
	"github.com/iotaledger/trie.go/models/trie_mimc"
)

const (
	proofSetSize = 258 // 256 children + terminal + fragment
	nbAccounts   = 16  // 16 accounts so we know that the proof length is 5
	depth        = 5   // size fo the inclusion proofs
	batchSize    = 1   // nbTranfers to batch in a proof
)

// Circuit "toy" rollup circuit where an operator can generate a proof that he processed
// some transactions
type Circuit struct {
	// ---------------------------------------------------------------------------------------------
	// SECRET INPUTS

	// list of accounts involved before update and their public keys
	SenderAccountsBefore   [batchSize]AccountConstraints
	ReceiverAccountsBefore [batchSize]AccountConstraints
	PublicKeysSender       [batchSize]eddsa.PublicKey

	// list of accounts involved after update and their public keys
	SenderAccountsAfter   [batchSize]AccountConstraints
	ReceiverAccountsAfter [batchSize]AccountConstraints
	PublicKeysReceiver    [batchSize]eddsa.PublicKey

	// list of transactions
	Transfers [batchSize]TransferConstraints

	// trie proofs corresponding to sender account
	TrieProofsSenderBefore [batchSize][proofSetSize][depth]frontend.Variable
	TrieProofsSenderAfter  [batchSize][proofSetSize][depth]frontend.Variable
	TriePathSenderBefore   [batchSize][depth - 1]frontend.Variable
	TriePathSenderAfter    [batchSize][depth - 1]frontend.Variable

	// trie proofs corresponding to receiver account
	TrieProofsReceiverBefore [batchSize][proofSetSize][depth]frontend.Variable
	TrieProofsReceiverAfter  [batchSize][proofSetSize][depth]frontend.Variable
	TriePathReceiverBefore   [batchSize][depth - 1]frontend.Variable
	TriePathReceiverAfter    [batchSize][depth - 1]frontend.Variable

	// ---------------------------------------------------------------------------------------------
	// PUBLIC INPUTS

	// list of root hashes of the trie
	TrieRootHashesBefore [batchSize]frontend.Variable `gnark:",public"`
	TrieRootHashesAfter  [batchSize]frontend.Variable `gnark:",public"`
}

// AccountConstraints accounts encoded as constraints
type AccountConstraints struct {
	Index   frontend.Variable // index in the tree
	Nonce   frontend.Variable // nb transactions done so far from this account
	Balance frontend.Variable
	PubKey  eddsa.PublicKey `gnark:"-"`
}

// TransferConstraints transfer encoded as constraints
type TransferConstraints struct {
	Amount         frontend.Variable
	Nonce          frontend.Variable `gnark:"-"`
	SenderPubKey   eddsa.PublicKey   `gnark:"-"`
	ReceiverPubKey eddsa.PublicKey   `gnark:"-"`
	Signature      eddsa.Signature
}

func (circuit *Circuit) postInit(api frontend.API) error {

	for i := 0; i < batchSize; i++ {

		// setting the sender accounts before update
		circuit.SenderAccountsBefore[i].PubKey = circuit.PublicKeysSender[i]

		// setting the sender accounts after update
		circuit.SenderAccountsAfter[i].PubKey = circuit.PublicKeysSender[i]

		// setting the receiver accounts before update
		circuit.ReceiverAccountsBefore[i].PubKey = circuit.PublicKeysReceiver[i]

		// setting the receiver accounts after update
		circuit.ReceiverAccountsAfter[i].PubKey = circuit.PublicKeysReceiver[i]

		// setting the transfers
		circuit.Transfers[i].Nonce = circuit.SenderAccountsBefore[i].Nonce
		circuit.Transfers[i].SenderPubKey = circuit.PublicKeysSender[i]
		circuit.Transfers[i].ReceiverPubKey = circuit.PublicKeysReceiver[i]

	}
	return nil
}

// Define declares the circuit's constraints
func (circuit *Circuit) Define(api frontend.API) error {
	if err := circuit.postInit(api); err != nil {
		return err
	}
	// hash function for the merkle proof and the eddsa signature
	hFunc, err := mimc.NewMiMC(api)
	if err != nil {
		return err
	}

	// creation of the circuit
	for i := 0; i < batchSize; i++ {

		// verify the proof created by trie.go
		trie_mimc.Validate256(api, hFunc, circuit.TrieRootHashesBefore[i],
			circuit.TrieProofsSenderBefore[i][0][:],
			circuit.TrieProofsSenderBefore[i][1][:],
			circuit.TrieProofsSenderBefore[i][2][:],
			circuit.TrieProofsSenderBefore[i][3][:],
			circuit.TrieProofsSenderBefore[i][4][:],
			circuit.TrieProofsSenderBefore[i][5][:],
			circuit.TrieProofsSenderBefore[i][6][:],
			circuit.TrieProofsSenderBefore[i][7][:],
			circuit.TrieProofsSenderBefore[i][8][:],
			circuit.TrieProofsSenderBefore[i][9][:],
			circuit.TrieProofsSenderBefore[i][10][:],
			circuit.TrieProofsSenderBefore[i][11][:],
			circuit.TrieProofsSenderBefore[i][12][:],
			circuit.TrieProofsSenderBefore[i][13][:],
			circuit.TrieProofsSenderBefore[i][14][:],
			circuit.TrieProofsSenderBefore[i][15][:],
			circuit.TrieProofsSenderBefore[i][16][:],
			circuit.TrieProofsSenderBefore[i][17][:],
			circuit.TrieProofsSenderBefore[i][18][:],
			circuit.TrieProofsSenderBefore[i][19][:],
			circuit.TrieProofsSenderBefore[i][20][:],
			circuit.TrieProofsSenderBefore[i][21][:],
			circuit.TrieProofsSenderBefore[i][22][:],
			circuit.TrieProofsSenderBefore[i][23][:],
			circuit.TrieProofsSenderBefore[i][24][:],
			circuit.TrieProofsSenderBefore[i][25][:],
			circuit.TrieProofsSenderBefore[i][26][:],
			circuit.TrieProofsSenderBefore[i][27][:],
			circuit.TrieProofsSenderBefore[i][28][:],
			circuit.TrieProofsSenderBefore[i][29][:],
			circuit.TrieProofsSenderBefore[i][30][:],
			circuit.TrieProofsSenderBefore[i][31][:],
			circuit.TrieProofsSenderBefore[i][32][:],
			circuit.TrieProofsSenderBefore[i][33][:],
			circuit.TrieProofsSenderBefore[i][34][:],
			circuit.TrieProofsSenderBefore[i][35][:],
			circuit.TrieProofsSenderBefore[i][36][:],
			circuit.TrieProofsSenderBefore[i][37][:],
			circuit.TrieProofsSenderBefore[i][38][:],
			circuit.TrieProofsSenderBefore[i][39][:],
			circuit.TrieProofsSenderBefore[i][40][:],
			circuit.TrieProofsSenderBefore[i][41][:],
			circuit.TrieProofsSenderBefore[i][42][:],
			circuit.TrieProofsSenderBefore[i][43][:],
			circuit.TrieProofsSenderBefore[i][44][:],
			circuit.TrieProofsSenderBefore[i][45][:],
			circuit.TrieProofsSenderBefore[i][46][:],
			circuit.TrieProofsSenderBefore[i][47][:],
			circuit.TrieProofsSenderBefore[i][48][:],
			circuit.TrieProofsSenderBefore[i][49][:],
			circuit.TrieProofsSenderBefore[i][50][:],
			circuit.TrieProofsSenderBefore[i][51][:],
			circuit.TrieProofsSenderBefore[i][52][:],
			circuit.TrieProofsSenderBefore[i][53][:],
			circuit.TrieProofsSenderBefore[i][54][:],
			circuit.TrieProofsSenderBefore[i][55][:],
			circuit.TrieProofsSenderBefore[i][56][:],
			circuit.TrieProofsSenderBefore[i][57][:],
			circuit.TrieProofsSenderBefore[i][58][:],
			circuit.TrieProofsSenderBefore[i][59][:],
			circuit.TrieProofsSenderBefore[i][60][:],
			circuit.TrieProofsSenderBefore[i][61][:],
			circuit.TrieProofsSenderBefore[i][62][:],
			circuit.TrieProofsSenderBefore[i][63][:],
			circuit.TrieProofsSenderBefore[i][64][:],
			circuit.TrieProofsSenderBefore[i][65][:],
			circuit.TrieProofsSenderBefore[i][66][:],
			circuit.TrieProofsSenderBefore[i][67][:],
			circuit.TrieProofsSenderBefore[i][68][:],
			circuit.TrieProofsSenderBefore[i][69][:],
			circuit.TrieProofsSenderBefore[i][70][:],
			circuit.TrieProofsSenderBefore[i][71][:],
			circuit.TrieProofsSenderBefore[i][72][:],
			circuit.TrieProofsSenderBefore[i][73][:],
			circuit.TrieProofsSenderBefore[i][74][:],
			circuit.TrieProofsSenderBefore[i][75][:],
			circuit.TrieProofsSenderBefore[i][76][:],
			circuit.TrieProofsSenderBefore[i][77][:],
			circuit.TrieProofsSenderBefore[i][78][:],
			circuit.TrieProofsSenderBefore[i][79][:],
			circuit.TrieProofsSenderBefore[i][80][:],
			circuit.TrieProofsSenderBefore[i][81][:],
			circuit.TrieProofsSenderBefore[i][82][:],
			circuit.TrieProofsSenderBefore[i][83][:],
			circuit.TrieProofsSenderBefore[i][84][:],
			circuit.TrieProofsSenderBefore[i][85][:],
			circuit.TrieProofsSenderBefore[i][86][:],
			circuit.TrieProofsSenderBefore[i][87][:],
			circuit.TrieProofsSenderBefore[i][88][:],
			circuit.TrieProofsSenderBefore[i][89][:],
			circuit.TrieProofsSenderBefore[i][90][:],
			circuit.TrieProofsSenderBefore[i][91][:],
			circuit.TrieProofsSenderBefore[i][92][:],
			circuit.TrieProofsSenderBefore[i][93][:],
			circuit.TrieProofsSenderBefore[i][94][:],
			circuit.TrieProofsSenderBefore[i][95][:],
			circuit.TrieProofsSenderBefore[i][96][:],
			circuit.TrieProofsSenderBefore[i][97][:],
			circuit.TrieProofsSenderBefore[i][98][:],
			circuit.TrieProofsSenderBefore[i][99][:],
			circuit.TrieProofsSenderBefore[i][100][:],
			circuit.TrieProofsSenderBefore[i][101][:],
			circuit.TrieProofsSenderBefore[i][102][:],
			circuit.TrieProofsSenderBefore[i][103][:],
			circuit.TrieProofsSenderBefore[i][104][:],
			circuit.TrieProofsSenderBefore[i][105][:],
			circuit.TrieProofsSenderBefore[i][106][:],
			circuit.TrieProofsSenderBefore[i][107][:],
			circuit.TrieProofsSenderBefore[i][108][:],
			circuit.TrieProofsSenderBefore[i][109][:],
			circuit.TrieProofsSenderBefore[i][110][:],
			circuit.TrieProofsSenderBefore[i][111][:],
			circuit.TrieProofsSenderBefore[i][112][:],
			circuit.TrieProofsSenderBefore[i][113][:],
			circuit.TrieProofsSenderBefore[i][114][:],
			circuit.TrieProofsSenderBefore[i][115][:],
			circuit.TrieProofsSenderBefore[i][116][:],
			circuit.TrieProofsSenderBefore[i][117][:],
			circuit.TrieProofsSenderBefore[i][118][:],
			circuit.TrieProofsSenderBefore[i][119][:],
			circuit.TrieProofsSenderBefore[i][120][:],
			circuit.TrieProofsSenderBefore[i][121][:],
			circuit.TrieProofsSenderBefore[i][122][:],
			circuit.TrieProofsSenderBefore[i][123][:],
			circuit.TrieProofsSenderBefore[i][124][:],
			circuit.TrieProofsSenderBefore[i][125][:],
			circuit.TrieProofsSenderBefore[i][126][:],
			circuit.TrieProofsSenderBefore[i][127][:],
			circuit.TrieProofsSenderBefore[i][128][:],
			circuit.TrieProofsSenderBefore[i][129][:],
			circuit.TrieProofsSenderBefore[i][130][:],
			circuit.TrieProofsSenderBefore[i][131][:],
			circuit.TrieProofsSenderBefore[i][132][:],
			circuit.TrieProofsSenderBefore[i][133][:],
			circuit.TrieProofsSenderBefore[i][134][:],
			circuit.TrieProofsSenderBefore[i][135][:],
			circuit.TrieProofsSenderBefore[i][136][:],
			circuit.TrieProofsSenderBefore[i][137][:],
			circuit.TrieProofsSenderBefore[i][138][:],
			circuit.TrieProofsSenderBefore[i][139][:],
			circuit.TrieProofsSenderBefore[i][140][:],
			circuit.TrieProofsSenderBefore[i][141][:],
			circuit.TrieProofsSenderBefore[i][142][:],
			circuit.TrieProofsSenderBefore[i][143][:],
			circuit.TrieProofsSenderBefore[i][144][:],
			circuit.TrieProofsSenderBefore[i][145][:],
			circuit.TrieProofsSenderBefore[i][146][:],
			circuit.TrieProofsSenderBefore[i][147][:],
			circuit.TrieProofsSenderBefore[i][148][:],
			circuit.TrieProofsSenderBefore[i][149][:],
			circuit.TrieProofsSenderBefore[i][150][:],
			circuit.TrieProofsSenderBefore[i][151][:],
			circuit.TrieProofsSenderBefore[i][152][:],
			circuit.TrieProofsSenderBefore[i][153][:],
			circuit.TrieProofsSenderBefore[i][154][:],
			circuit.TrieProofsSenderBefore[i][155][:],
			circuit.TrieProofsSenderBefore[i][156][:],
			circuit.TrieProofsSenderBefore[i][157][:],
			circuit.TrieProofsSenderBefore[i][158][:],
			circuit.TrieProofsSenderBefore[i][159][:],
			circuit.TrieProofsSenderBefore[i][160][:],
			circuit.TrieProofsSenderBefore[i][161][:],
			circuit.TrieProofsSenderBefore[i][162][:],
			circuit.TrieProofsSenderBefore[i][163][:],
			circuit.TrieProofsSenderBefore[i][164][:],
			circuit.TrieProofsSenderBefore[i][165][:],
			circuit.TrieProofsSenderBefore[i][166][:],
			circuit.TrieProofsSenderBefore[i][167][:],
			circuit.TrieProofsSenderBefore[i][168][:],
			circuit.TrieProofsSenderBefore[i][169][:],
			circuit.TrieProofsSenderBefore[i][170][:],
			circuit.TrieProofsSenderBefore[i][171][:],
			circuit.TrieProofsSenderBefore[i][172][:],
			circuit.TrieProofsSenderBefore[i][173][:],
			circuit.TrieProofsSenderBefore[i][174][:],
			circuit.TrieProofsSenderBefore[i][175][:],
			circuit.TrieProofsSenderBefore[i][176][:],
			circuit.TrieProofsSenderBefore[i][177][:],
			circuit.TrieProofsSenderBefore[i][178][:],
			circuit.TrieProofsSenderBefore[i][179][:],
			circuit.TrieProofsSenderBefore[i][180][:],
			circuit.TrieProofsSenderBefore[i][181][:],
			circuit.TrieProofsSenderBefore[i][182][:],
			circuit.TrieProofsSenderBefore[i][183][:],
			circuit.TrieProofsSenderBefore[i][184][:],
			circuit.TrieProofsSenderBefore[i][185][:],
			circuit.TrieProofsSenderBefore[i][186][:],
			circuit.TrieProofsSenderBefore[i][187][:],
			circuit.TrieProofsSenderBefore[i][188][:],
			circuit.TrieProofsSenderBefore[i][189][:],
			circuit.TrieProofsSenderBefore[i][190][:],
			circuit.TrieProofsSenderBefore[i][191][:],
			circuit.TrieProofsSenderBefore[i][192][:],
			circuit.TrieProofsSenderBefore[i][193][:],
			circuit.TrieProofsSenderBefore[i][194][:],
			circuit.TrieProofsSenderBefore[i][195][:],
			circuit.TrieProofsSenderBefore[i][196][:],
			circuit.TrieProofsSenderBefore[i][197][:],
			circuit.TrieProofsSenderBefore[i][198][:],
			circuit.TrieProofsSenderBefore[i][199][:],
			circuit.TrieProofsSenderBefore[i][200][:],
			circuit.TrieProofsSenderBefore[i][201][:],
			circuit.TrieProofsSenderBefore[i][202][:],
			circuit.TrieProofsSenderBefore[i][203][:],
			circuit.TrieProofsSenderBefore[i][204][:],
			circuit.TrieProofsSenderBefore[i][205][:],
			circuit.TrieProofsSenderBefore[i][206][:],
			circuit.TrieProofsSenderBefore[i][207][:],
			circuit.TrieProofsSenderBefore[i][208][:],
			circuit.TrieProofsSenderBefore[i][209][:],
			circuit.TrieProofsSenderBefore[i][210][:],
			circuit.TrieProofsSenderBefore[i][211][:],
			circuit.TrieProofsSenderBefore[i][212][:],
			circuit.TrieProofsSenderBefore[i][213][:],
			circuit.TrieProofsSenderBefore[i][214][:],
			circuit.TrieProofsSenderBefore[i][215][:],
			circuit.TrieProofsSenderBefore[i][216][:],
			circuit.TrieProofsSenderBefore[i][217][:],
			circuit.TrieProofsSenderBefore[i][218][:],
			circuit.TrieProofsSenderBefore[i][219][:],
			circuit.TrieProofsSenderBefore[i][220][:],
			circuit.TrieProofsSenderBefore[i][221][:],
			circuit.TrieProofsSenderBefore[i][222][:],
			circuit.TrieProofsSenderBefore[i][223][:],
			circuit.TrieProofsSenderBefore[i][224][:],
			circuit.TrieProofsSenderBefore[i][225][:],
			circuit.TrieProofsSenderBefore[i][226][:],
			circuit.TrieProofsSenderBefore[i][227][:],
			circuit.TrieProofsSenderBefore[i][228][:],
			circuit.TrieProofsSenderBefore[i][229][:],
			circuit.TrieProofsSenderBefore[i][230][:],
			circuit.TrieProofsSenderBefore[i][231][:],
			circuit.TrieProofsSenderBefore[i][232][:],
			circuit.TrieProofsSenderBefore[i][233][:],
			circuit.TrieProofsSenderBefore[i][234][:],
			circuit.TrieProofsSenderBefore[i][235][:],
			circuit.TrieProofsSenderBefore[i][236][:],
			circuit.TrieProofsSenderBefore[i][237][:],
			circuit.TrieProofsSenderBefore[i][238][:],
			circuit.TrieProofsSenderBefore[i][239][:],
			circuit.TrieProofsSenderBefore[i][240][:],
			circuit.TrieProofsSenderBefore[i][241][:],
			circuit.TrieProofsSenderBefore[i][242][:],
			circuit.TrieProofsSenderBefore[i][243][:],
			circuit.TrieProofsSenderBefore[i][244][:],
			circuit.TrieProofsSenderBefore[i][245][:],
			circuit.TrieProofsSenderBefore[i][246][:],
			circuit.TrieProofsSenderBefore[i][247][:],
			circuit.TrieProofsSenderBefore[i][248][:],
			circuit.TrieProofsSenderBefore[i][249][:],
			circuit.TrieProofsSenderBefore[i][250][:],
			circuit.TrieProofsSenderBefore[i][251][:],
			circuit.TrieProofsSenderBefore[i][252][:],
			circuit.TrieProofsSenderBefore[i][253][:],
			circuit.TrieProofsSenderBefore[i][254][:],
			circuit.TrieProofsSenderBefore[i][255][:],
			circuit.TrieProofsSenderBefore[i][256][:],
			circuit.TrieProofsSenderBefore[i][257][:],
			circuit.TriePathSenderBefore[i][:])
		trie_mimc.Validate256(api, hFunc, circuit.TrieRootHashesBefore[i],
			circuit.TrieProofsReceiverBefore[i][0][:],
			circuit.TrieProofsReceiverBefore[i][1][:],
			circuit.TrieProofsReceiverBefore[i][2][:],
			circuit.TrieProofsReceiverBefore[i][3][:],
			circuit.TrieProofsReceiverBefore[i][4][:],
			circuit.TrieProofsReceiverBefore[i][5][:],
			circuit.TrieProofsReceiverBefore[i][6][:],
			circuit.TrieProofsReceiverBefore[i][7][:],
			circuit.TrieProofsReceiverBefore[i][8][:],
			circuit.TrieProofsReceiverBefore[i][9][:],
			circuit.TrieProofsReceiverBefore[i][10][:],
			circuit.TrieProofsReceiverBefore[i][11][:],
			circuit.TrieProofsReceiverBefore[i][12][:],
			circuit.TrieProofsReceiverBefore[i][13][:],
			circuit.TrieProofsReceiverBefore[i][14][:],
			circuit.TrieProofsReceiverBefore[i][15][:],
			circuit.TrieProofsReceiverBefore[i][16][:],
			circuit.TrieProofsReceiverBefore[i][17][:],
			circuit.TrieProofsReceiverBefore[i][18][:],
			circuit.TrieProofsReceiverBefore[i][19][:],
			circuit.TrieProofsReceiverBefore[i][20][:],
			circuit.TrieProofsReceiverBefore[i][21][:],
			circuit.TrieProofsReceiverBefore[i][22][:],
			circuit.TrieProofsReceiverBefore[i][23][:],
			circuit.TrieProofsReceiverBefore[i][24][:],
			circuit.TrieProofsReceiverBefore[i][25][:],
			circuit.TrieProofsReceiverBefore[i][26][:],
			circuit.TrieProofsReceiverBefore[i][27][:],
			circuit.TrieProofsReceiverBefore[i][28][:],
			circuit.TrieProofsReceiverBefore[i][29][:],
			circuit.TrieProofsReceiverBefore[i][30][:],
			circuit.TrieProofsReceiverBefore[i][31][:],
			circuit.TrieProofsReceiverBefore[i][32][:],
			circuit.TrieProofsReceiverBefore[i][33][:],
			circuit.TrieProofsReceiverBefore[i][34][:],
			circuit.TrieProofsReceiverBefore[i][35][:],
			circuit.TrieProofsReceiverBefore[i][36][:],
			circuit.TrieProofsReceiverBefore[i][37][:],
			circuit.TrieProofsReceiverBefore[i][38][:],
			circuit.TrieProofsReceiverBefore[i][39][:],
			circuit.TrieProofsReceiverBefore[i][40][:],
			circuit.TrieProofsReceiverBefore[i][41][:],
			circuit.TrieProofsReceiverBefore[i][42][:],
			circuit.TrieProofsReceiverBefore[i][43][:],
			circuit.TrieProofsReceiverBefore[i][44][:],
			circuit.TrieProofsReceiverBefore[i][45][:],
			circuit.TrieProofsReceiverBefore[i][46][:],
			circuit.TrieProofsReceiverBefore[i][47][:],
			circuit.TrieProofsReceiverBefore[i][48][:],
			circuit.TrieProofsReceiverBefore[i][49][:],
			circuit.TrieProofsReceiverBefore[i][50][:],
			circuit.TrieProofsReceiverBefore[i][51][:],
			circuit.TrieProofsReceiverBefore[i][52][:],
			circuit.TrieProofsReceiverBefore[i][53][:],
			circuit.TrieProofsReceiverBefore[i][54][:],
			circuit.TrieProofsReceiverBefore[i][55][:],
			circuit.TrieProofsReceiverBefore[i][56][:],
			circuit.TrieProofsReceiverBefore[i][57][:],
			circuit.TrieProofsReceiverBefore[i][58][:],
			circuit.TrieProofsReceiverBefore[i][59][:],
			circuit.TrieProofsReceiverBefore[i][60][:],
			circuit.TrieProofsReceiverBefore[i][61][:],
			circuit.TrieProofsReceiverBefore[i][62][:],
			circuit.TrieProofsReceiverBefore[i][63][:],
			circuit.TrieProofsReceiverBefore[i][64][:],
			circuit.TrieProofsReceiverBefore[i][65][:],
			circuit.TrieProofsReceiverBefore[i][66][:],
			circuit.TrieProofsReceiverBefore[i][67][:],
			circuit.TrieProofsReceiverBefore[i][68][:],
			circuit.TrieProofsReceiverBefore[i][69][:],
			circuit.TrieProofsReceiverBefore[i][70][:],
			circuit.TrieProofsReceiverBefore[i][71][:],
			circuit.TrieProofsReceiverBefore[i][72][:],
			circuit.TrieProofsReceiverBefore[i][73][:],
			circuit.TrieProofsReceiverBefore[i][74][:],
			circuit.TrieProofsReceiverBefore[i][75][:],
			circuit.TrieProofsReceiverBefore[i][76][:],
			circuit.TrieProofsReceiverBefore[i][77][:],
			circuit.TrieProofsReceiverBefore[i][78][:],
			circuit.TrieProofsReceiverBefore[i][79][:],
			circuit.TrieProofsReceiverBefore[i][80][:],
			circuit.TrieProofsReceiverBefore[i][81][:],
			circuit.TrieProofsReceiverBefore[i][82][:],
			circuit.TrieProofsReceiverBefore[i][83][:],
			circuit.TrieProofsReceiverBefore[i][84][:],
			circuit.TrieProofsReceiverBefore[i][85][:],
			circuit.TrieProofsReceiverBefore[i][86][:],
			circuit.TrieProofsReceiverBefore[i][87][:],
			circuit.TrieProofsReceiverBefore[i][88][:],
			circuit.TrieProofsReceiverBefore[i][89][:],
			circuit.TrieProofsReceiverBefore[i][90][:],
			circuit.TrieProofsReceiverBefore[i][91][:],
			circuit.TrieProofsReceiverBefore[i][92][:],
			circuit.TrieProofsReceiverBefore[i][93][:],
			circuit.TrieProofsReceiverBefore[i][94][:],
			circuit.TrieProofsReceiverBefore[i][95][:],
			circuit.TrieProofsReceiverBefore[i][96][:],
			circuit.TrieProofsReceiverBefore[i][97][:],
			circuit.TrieProofsReceiverBefore[i][98][:],
			circuit.TrieProofsReceiverBefore[i][99][:],
			circuit.TrieProofsReceiverBefore[i][100][:],
			circuit.TrieProofsReceiverBefore[i][101][:],
			circuit.TrieProofsReceiverBefore[i][102][:],
			circuit.TrieProofsReceiverBefore[i][103][:],
			circuit.TrieProofsReceiverBefore[i][104][:],
			circuit.TrieProofsReceiverBefore[i][105][:],
			circuit.TrieProofsReceiverBefore[i][106][:],
			circuit.TrieProofsReceiverBefore[i][107][:],
			circuit.TrieProofsReceiverBefore[i][108][:],
			circuit.TrieProofsReceiverBefore[i][109][:],
			circuit.TrieProofsReceiverBefore[i][110][:],
			circuit.TrieProofsReceiverBefore[i][111][:],
			circuit.TrieProofsReceiverBefore[i][112][:],
			circuit.TrieProofsReceiverBefore[i][113][:],
			circuit.TrieProofsReceiverBefore[i][114][:],
			circuit.TrieProofsReceiverBefore[i][115][:],
			circuit.TrieProofsReceiverBefore[i][116][:],
			circuit.TrieProofsReceiverBefore[i][117][:],
			circuit.TrieProofsReceiverBefore[i][118][:],
			circuit.TrieProofsReceiverBefore[i][119][:],
			circuit.TrieProofsReceiverBefore[i][120][:],
			circuit.TrieProofsReceiverBefore[i][121][:],
			circuit.TrieProofsReceiverBefore[i][122][:],
			circuit.TrieProofsReceiverBefore[i][123][:],
			circuit.TrieProofsReceiverBefore[i][124][:],
			circuit.TrieProofsReceiverBefore[i][125][:],
			circuit.TrieProofsReceiverBefore[i][126][:],
			circuit.TrieProofsReceiverBefore[i][127][:],
			circuit.TrieProofsReceiverBefore[i][128][:],
			circuit.TrieProofsReceiverBefore[i][129][:],
			circuit.TrieProofsReceiverBefore[i][130][:],
			circuit.TrieProofsReceiverBefore[i][131][:],
			circuit.TrieProofsReceiverBefore[i][132][:],
			circuit.TrieProofsReceiverBefore[i][133][:],
			circuit.TrieProofsReceiverBefore[i][134][:],
			circuit.TrieProofsReceiverBefore[i][135][:],
			circuit.TrieProofsReceiverBefore[i][136][:],
			circuit.TrieProofsReceiverBefore[i][137][:],
			circuit.TrieProofsReceiverBefore[i][138][:],
			circuit.TrieProofsReceiverBefore[i][139][:],
			circuit.TrieProofsReceiverBefore[i][140][:],
			circuit.TrieProofsReceiverBefore[i][141][:],
			circuit.TrieProofsReceiverBefore[i][142][:],
			circuit.TrieProofsReceiverBefore[i][143][:],
			circuit.TrieProofsReceiverBefore[i][144][:],
			circuit.TrieProofsReceiverBefore[i][145][:],
			circuit.TrieProofsReceiverBefore[i][146][:],
			circuit.TrieProofsReceiverBefore[i][147][:],
			circuit.TrieProofsReceiverBefore[i][148][:],
			circuit.TrieProofsReceiverBefore[i][149][:],
			circuit.TrieProofsReceiverBefore[i][150][:],
			circuit.TrieProofsReceiverBefore[i][151][:],
			circuit.TrieProofsReceiverBefore[i][152][:],
			circuit.TrieProofsReceiverBefore[i][153][:],
			circuit.TrieProofsReceiverBefore[i][154][:],
			circuit.TrieProofsReceiverBefore[i][155][:],
			circuit.TrieProofsReceiverBefore[i][156][:],
			circuit.TrieProofsReceiverBefore[i][157][:],
			circuit.TrieProofsReceiverBefore[i][158][:],
			circuit.TrieProofsReceiverBefore[i][159][:],
			circuit.TrieProofsReceiverBefore[i][160][:],
			circuit.TrieProofsReceiverBefore[i][161][:],
			circuit.TrieProofsReceiverBefore[i][162][:],
			circuit.TrieProofsReceiverBefore[i][163][:],
			circuit.TrieProofsReceiverBefore[i][164][:],
			circuit.TrieProofsReceiverBefore[i][165][:],
			circuit.TrieProofsReceiverBefore[i][166][:],
			circuit.TrieProofsReceiverBefore[i][167][:],
			circuit.TrieProofsReceiverBefore[i][168][:],
			circuit.TrieProofsReceiverBefore[i][169][:],
			circuit.TrieProofsReceiverBefore[i][170][:],
			circuit.TrieProofsReceiverBefore[i][171][:],
			circuit.TrieProofsReceiverBefore[i][172][:],
			circuit.TrieProofsReceiverBefore[i][173][:],
			circuit.TrieProofsReceiverBefore[i][174][:],
			circuit.TrieProofsReceiverBefore[i][175][:],
			circuit.TrieProofsReceiverBefore[i][176][:],
			circuit.TrieProofsReceiverBefore[i][177][:],
			circuit.TrieProofsReceiverBefore[i][178][:],
			circuit.TrieProofsReceiverBefore[i][179][:],
			circuit.TrieProofsReceiverBefore[i][180][:],
			circuit.TrieProofsReceiverBefore[i][181][:],
			circuit.TrieProofsReceiverBefore[i][182][:],
			circuit.TrieProofsReceiverBefore[i][183][:],
			circuit.TrieProofsReceiverBefore[i][184][:],
			circuit.TrieProofsReceiverBefore[i][185][:],
			circuit.TrieProofsReceiverBefore[i][186][:],
			circuit.TrieProofsReceiverBefore[i][187][:],
			circuit.TrieProofsReceiverBefore[i][188][:],
			circuit.TrieProofsReceiverBefore[i][189][:],
			circuit.TrieProofsReceiverBefore[i][190][:],
			circuit.TrieProofsReceiverBefore[i][191][:],
			circuit.TrieProofsReceiverBefore[i][192][:],
			circuit.TrieProofsReceiverBefore[i][193][:],
			circuit.TrieProofsReceiverBefore[i][194][:],
			circuit.TrieProofsReceiverBefore[i][195][:],
			circuit.TrieProofsReceiverBefore[i][196][:],
			circuit.TrieProofsReceiverBefore[i][197][:],
			circuit.TrieProofsReceiverBefore[i][198][:],
			circuit.TrieProofsReceiverBefore[i][199][:],
			circuit.TrieProofsReceiverBefore[i][200][:],
			circuit.TrieProofsReceiverBefore[i][201][:],
			circuit.TrieProofsReceiverBefore[i][202][:],
			circuit.TrieProofsReceiverBefore[i][203][:],
			circuit.TrieProofsReceiverBefore[i][204][:],
			circuit.TrieProofsReceiverBefore[i][205][:],
			circuit.TrieProofsReceiverBefore[i][206][:],
			circuit.TrieProofsReceiverBefore[i][207][:],
			circuit.TrieProofsReceiverBefore[i][208][:],
			circuit.TrieProofsReceiverBefore[i][209][:],
			circuit.TrieProofsReceiverBefore[i][210][:],
			circuit.TrieProofsReceiverBefore[i][211][:],
			circuit.TrieProofsReceiverBefore[i][212][:],
			circuit.TrieProofsReceiverBefore[i][213][:],
			circuit.TrieProofsReceiverBefore[i][214][:],
			circuit.TrieProofsReceiverBefore[i][215][:],
			circuit.TrieProofsReceiverBefore[i][216][:],
			circuit.TrieProofsReceiverBefore[i][217][:],
			circuit.TrieProofsReceiverBefore[i][218][:],
			circuit.TrieProofsReceiverBefore[i][219][:],
			circuit.TrieProofsReceiverBefore[i][220][:],
			circuit.TrieProofsReceiverBefore[i][221][:],
			circuit.TrieProofsReceiverBefore[i][222][:],
			circuit.TrieProofsReceiverBefore[i][223][:],
			circuit.TrieProofsReceiverBefore[i][224][:],
			circuit.TrieProofsReceiverBefore[i][225][:],
			circuit.TrieProofsReceiverBefore[i][226][:],
			circuit.TrieProofsReceiverBefore[i][227][:],
			circuit.TrieProofsReceiverBefore[i][228][:],
			circuit.TrieProofsReceiverBefore[i][229][:],
			circuit.TrieProofsReceiverBefore[i][230][:],
			circuit.TrieProofsReceiverBefore[i][231][:],
			circuit.TrieProofsReceiverBefore[i][232][:],
			circuit.TrieProofsReceiverBefore[i][233][:],
			circuit.TrieProofsReceiverBefore[i][234][:],
			circuit.TrieProofsReceiverBefore[i][235][:],
			circuit.TrieProofsReceiverBefore[i][236][:],
			circuit.TrieProofsReceiverBefore[i][237][:],
			circuit.TrieProofsReceiverBefore[i][238][:],
			circuit.TrieProofsReceiverBefore[i][239][:],
			circuit.TrieProofsReceiverBefore[i][240][:],
			circuit.TrieProofsReceiverBefore[i][241][:],
			circuit.TrieProofsReceiverBefore[i][242][:],
			circuit.TrieProofsReceiverBefore[i][243][:],
			circuit.TrieProofsReceiverBefore[i][244][:],
			circuit.TrieProofsReceiverBefore[i][245][:],
			circuit.TrieProofsReceiverBefore[i][246][:],
			circuit.TrieProofsReceiverBefore[i][247][:],
			circuit.TrieProofsReceiverBefore[i][248][:],
			circuit.TrieProofsReceiverBefore[i][249][:],
			circuit.TrieProofsReceiverBefore[i][250][:],
			circuit.TrieProofsReceiverBefore[i][251][:],
			circuit.TrieProofsReceiverBefore[i][252][:],
			circuit.TrieProofsReceiverBefore[i][253][:],
			circuit.TrieProofsReceiverBefore[i][254][:],
			circuit.TrieProofsReceiverBefore[i][255][:],
			circuit.TrieProofsReceiverBefore[i][256][:],
			circuit.TrieProofsReceiverBefore[i][257][:],
			circuit.TriePathReceiverBefore[i][:])

		trie_mimc.Validate256(api, hFunc, circuit.TrieRootHashesAfter[i],
			circuit.TrieProofsSenderAfter[i][0][:],
			circuit.TrieProofsSenderAfter[i][1][:],
			circuit.TrieProofsSenderAfter[i][2][:],
			circuit.TrieProofsSenderAfter[i][3][:],
			circuit.TrieProofsSenderAfter[i][4][:],
			circuit.TrieProofsSenderAfter[i][5][:],
			circuit.TrieProofsSenderAfter[i][6][:],
			circuit.TrieProofsSenderAfter[i][7][:],
			circuit.TrieProofsSenderAfter[i][8][:],
			circuit.TrieProofsSenderAfter[i][9][:],
			circuit.TrieProofsSenderAfter[i][10][:],
			circuit.TrieProofsSenderAfter[i][11][:],
			circuit.TrieProofsSenderAfter[i][12][:],
			circuit.TrieProofsSenderAfter[i][13][:],
			circuit.TrieProofsSenderAfter[i][14][:],
			circuit.TrieProofsSenderAfter[i][15][:],
			circuit.TrieProofsSenderAfter[i][16][:],
			circuit.TrieProofsSenderAfter[i][17][:],
			circuit.TrieProofsSenderAfter[i][18][:],
			circuit.TrieProofsSenderAfter[i][19][:],
			circuit.TrieProofsSenderAfter[i][20][:],
			circuit.TrieProofsSenderAfter[i][21][:],
			circuit.TrieProofsSenderAfter[i][22][:],
			circuit.TrieProofsSenderAfter[i][23][:],
			circuit.TrieProofsSenderAfter[i][24][:],
			circuit.TrieProofsSenderAfter[i][25][:],
			circuit.TrieProofsSenderAfter[i][26][:],
			circuit.TrieProofsSenderAfter[i][27][:],
			circuit.TrieProofsSenderAfter[i][28][:],
			circuit.TrieProofsSenderAfter[i][29][:],
			circuit.TrieProofsSenderAfter[i][30][:],
			circuit.TrieProofsSenderAfter[i][31][:],
			circuit.TrieProofsSenderAfter[i][32][:],
			circuit.TrieProofsSenderAfter[i][33][:],
			circuit.TrieProofsSenderAfter[i][34][:],
			circuit.TrieProofsSenderAfter[i][35][:],
			circuit.TrieProofsSenderAfter[i][36][:],
			circuit.TrieProofsSenderAfter[i][37][:],
			circuit.TrieProofsSenderAfter[i][38][:],
			circuit.TrieProofsSenderAfter[i][39][:],
			circuit.TrieProofsSenderAfter[i][40][:],
			circuit.TrieProofsSenderAfter[i][41][:],
			circuit.TrieProofsSenderAfter[i][42][:],
			circuit.TrieProofsSenderAfter[i][43][:],
			circuit.TrieProofsSenderAfter[i][44][:],
			circuit.TrieProofsSenderAfter[i][45][:],
			circuit.TrieProofsSenderAfter[i][46][:],
			circuit.TrieProofsSenderAfter[i][47][:],
			circuit.TrieProofsSenderAfter[i][48][:],
			circuit.TrieProofsSenderAfter[i][49][:],
			circuit.TrieProofsSenderAfter[i][50][:],
			circuit.TrieProofsSenderAfter[i][51][:],
			circuit.TrieProofsSenderAfter[i][52][:],
			circuit.TrieProofsSenderAfter[i][53][:],
			circuit.TrieProofsSenderAfter[i][54][:],
			circuit.TrieProofsSenderAfter[i][55][:],
			circuit.TrieProofsSenderAfter[i][56][:],
			circuit.TrieProofsSenderAfter[i][57][:],
			circuit.TrieProofsSenderAfter[i][58][:],
			circuit.TrieProofsSenderAfter[i][59][:],
			circuit.TrieProofsSenderAfter[i][60][:],
			circuit.TrieProofsSenderAfter[i][61][:],
			circuit.TrieProofsSenderAfter[i][62][:],
			circuit.TrieProofsSenderAfter[i][63][:],
			circuit.TrieProofsSenderAfter[i][64][:],
			circuit.TrieProofsSenderAfter[i][65][:],
			circuit.TrieProofsSenderAfter[i][66][:],
			circuit.TrieProofsSenderAfter[i][67][:],
			circuit.TrieProofsSenderAfter[i][68][:],
			circuit.TrieProofsSenderAfter[i][69][:],
			circuit.TrieProofsSenderAfter[i][70][:],
			circuit.TrieProofsSenderAfter[i][71][:],
			circuit.TrieProofsSenderAfter[i][72][:],
			circuit.TrieProofsSenderAfter[i][73][:],
			circuit.TrieProofsSenderAfter[i][74][:],
			circuit.TrieProofsSenderAfter[i][75][:],
			circuit.TrieProofsSenderAfter[i][76][:],
			circuit.TrieProofsSenderAfter[i][77][:],
			circuit.TrieProofsSenderAfter[i][78][:],
			circuit.TrieProofsSenderAfter[i][79][:],
			circuit.TrieProofsSenderAfter[i][80][:],
			circuit.TrieProofsSenderAfter[i][81][:],
			circuit.TrieProofsSenderAfter[i][82][:],
			circuit.TrieProofsSenderAfter[i][83][:],
			circuit.TrieProofsSenderAfter[i][84][:],
			circuit.TrieProofsSenderAfter[i][85][:],
			circuit.TrieProofsSenderAfter[i][86][:],
			circuit.TrieProofsSenderAfter[i][87][:],
			circuit.TrieProofsSenderAfter[i][88][:],
			circuit.TrieProofsSenderAfter[i][89][:],
			circuit.TrieProofsSenderAfter[i][90][:],
			circuit.TrieProofsSenderAfter[i][91][:],
			circuit.TrieProofsSenderAfter[i][92][:],
			circuit.TrieProofsSenderAfter[i][93][:],
			circuit.TrieProofsSenderAfter[i][94][:],
			circuit.TrieProofsSenderAfter[i][95][:],
			circuit.TrieProofsSenderAfter[i][96][:],
			circuit.TrieProofsSenderAfter[i][97][:],
			circuit.TrieProofsSenderAfter[i][98][:],
			circuit.TrieProofsSenderAfter[i][99][:],
			circuit.TrieProofsSenderAfter[i][100][:],
			circuit.TrieProofsSenderAfter[i][101][:],
			circuit.TrieProofsSenderAfter[i][102][:],
			circuit.TrieProofsSenderAfter[i][103][:],
			circuit.TrieProofsSenderAfter[i][104][:],
			circuit.TrieProofsSenderAfter[i][105][:],
			circuit.TrieProofsSenderAfter[i][106][:],
			circuit.TrieProofsSenderAfter[i][107][:],
			circuit.TrieProofsSenderAfter[i][108][:],
			circuit.TrieProofsSenderAfter[i][109][:],
			circuit.TrieProofsSenderAfter[i][110][:],
			circuit.TrieProofsSenderAfter[i][111][:],
			circuit.TrieProofsSenderAfter[i][112][:],
			circuit.TrieProofsSenderAfter[i][113][:],
			circuit.TrieProofsSenderAfter[i][114][:],
			circuit.TrieProofsSenderAfter[i][115][:],
			circuit.TrieProofsSenderAfter[i][116][:],
			circuit.TrieProofsSenderAfter[i][117][:],
			circuit.TrieProofsSenderAfter[i][118][:],
			circuit.TrieProofsSenderAfter[i][119][:],
			circuit.TrieProofsSenderAfter[i][120][:],
			circuit.TrieProofsSenderAfter[i][121][:],
			circuit.TrieProofsSenderAfter[i][122][:],
			circuit.TrieProofsSenderAfter[i][123][:],
			circuit.TrieProofsSenderAfter[i][124][:],
			circuit.TrieProofsSenderAfter[i][125][:],
			circuit.TrieProofsSenderAfter[i][126][:],
			circuit.TrieProofsSenderAfter[i][127][:],
			circuit.TrieProofsSenderAfter[i][128][:],
			circuit.TrieProofsSenderAfter[i][129][:],
			circuit.TrieProofsSenderAfter[i][130][:],
			circuit.TrieProofsSenderAfter[i][131][:],
			circuit.TrieProofsSenderAfter[i][132][:],
			circuit.TrieProofsSenderAfter[i][133][:],
			circuit.TrieProofsSenderAfter[i][134][:],
			circuit.TrieProofsSenderAfter[i][135][:],
			circuit.TrieProofsSenderAfter[i][136][:],
			circuit.TrieProofsSenderAfter[i][137][:],
			circuit.TrieProofsSenderAfter[i][138][:],
			circuit.TrieProofsSenderAfter[i][139][:],
			circuit.TrieProofsSenderAfter[i][140][:],
			circuit.TrieProofsSenderAfter[i][141][:],
			circuit.TrieProofsSenderAfter[i][142][:],
			circuit.TrieProofsSenderAfter[i][143][:],
			circuit.TrieProofsSenderAfter[i][144][:],
			circuit.TrieProofsSenderAfter[i][145][:],
			circuit.TrieProofsSenderAfter[i][146][:],
			circuit.TrieProofsSenderAfter[i][147][:],
			circuit.TrieProofsSenderAfter[i][148][:],
			circuit.TrieProofsSenderAfter[i][149][:],
			circuit.TrieProofsSenderAfter[i][150][:],
			circuit.TrieProofsSenderAfter[i][151][:],
			circuit.TrieProofsSenderAfter[i][152][:],
			circuit.TrieProofsSenderAfter[i][153][:],
			circuit.TrieProofsSenderAfter[i][154][:],
			circuit.TrieProofsSenderAfter[i][155][:],
			circuit.TrieProofsSenderAfter[i][156][:],
			circuit.TrieProofsSenderAfter[i][157][:],
			circuit.TrieProofsSenderAfter[i][158][:],
			circuit.TrieProofsSenderAfter[i][159][:],
			circuit.TrieProofsSenderAfter[i][160][:],
			circuit.TrieProofsSenderAfter[i][161][:],
			circuit.TrieProofsSenderAfter[i][162][:],
			circuit.TrieProofsSenderAfter[i][163][:],
			circuit.TrieProofsSenderAfter[i][164][:],
			circuit.TrieProofsSenderAfter[i][165][:],
			circuit.TrieProofsSenderAfter[i][166][:],
			circuit.TrieProofsSenderAfter[i][167][:],
			circuit.TrieProofsSenderAfter[i][168][:],
			circuit.TrieProofsSenderAfter[i][169][:],
			circuit.TrieProofsSenderAfter[i][170][:],
			circuit.TrieProofsSenderAfter[i][171][:],
			circuit.TrieProofsSenderAfter[i][172][:],
			circuit.TrieProofsSenderAfter[i][173][:],
			circuit.TrieProofsSenderAfter[i][174][:],
			circuit.TrieProofsSenderAfter[i][175][:],
			circuit.TrieProofsSenderAfter[i][176][:],
			circuit.TrieProofsSenderAfter[i][177][:],
			circuit.TrieProofsSenderAfter[i][178][:],
			circuit.TrieProofsSenderAfter[i][179][:],
			circuit.TrieProofsSenderAfter[i][180][:],
			circuit.TrieProofsSenderAfter[i][181][:],
			circuit.TrieProofsSenderAfter[i][182][:],
			circuit.TrieProofsSenderAfter[i][183][:],
			circuit.TrieProofsSenderAfter[i][184][:],
			circuit.TrieProofsSenderAfter[i][185][:],
			circuit.TrieProofsSenderAfter[i][186][:],
			circuit.TrieProofsSenderAfter[i][187][:],
			circuit.TrieProofsSenderAfter[i][188][:],
			circuit.TrieProofsSenderAfter[i][189][:],
			circuit.TrieProofsSenderAfter[i][190][:],
			circuit.TrieProofsSenderAfter[i][191][:],
			circuit.TrieProofsSenderAfter[i][192][:],
			circuit.TrieProofsSenderAfter[i][193][:],
			circuit.TrieProofsSenderAfter[i][194][:],
			circuit.TrieProofsSenderAfter[i][195][:],
			circuit.TrieProofsSenderAfter[i][196][:],
			circuit.TrieProofsSenderAfter[i][197][:],
			circuit.TrieProofsSenderAfter[i][198][:],
			circuit.TrieProofsSenderAfter[i][199][:],
			circuit.TrieProofsSenderAfter[i][200][:],
			circuit.TrieProofsSenderAfter[i][201][:],
			circuit.TrieProofsSenderAfter[i][202][:],
			circuit.TrieProofsSenderAfter[i][203][:],
			circuit.TrieProofsSenderAfter[i][204][:],
			circuit.TrieProofsSenderAfter[i][205][:],
			circuit.TrieProofsSenderAfter[i][206][:],
			circuit.TrieProofsSenderAfter[i][207][:],
			circuit.TrieProofsSenderAfter[i][208][:],
			circuit.TrieProofsSenderAfter[i][209][:],
			circuit.TrieProofsSenderAfter[i][210][:],
			circuit.TrieProofsSenderAfter[i][211][:],
			circuit.TrieProofsSenderAfter[i][212][:],
			circuit.TrieProofsSenderAfter[i][213][:],
			circuit.TrieProofsSenderAfter[i][214][:],
			circuit.TrieProofsSenderAfter[i][215][:],
			circuit.TrieProofsSenderAfter[i][216][:],
			circuit.TrieProofsSenderAfter[i][217][:],
			circuit.TrieProofsSenderAfter[i][218][:],
			circuit.TrieProofsSenderAfter[i][219][:],
			circuit.TrieProofsSenderAfter[i][220][:],
			circuit.TrieProofsSenderAfter[i][221][:],
			circuit.TrieProofsSenderAfter[i][222][:],
			circuit.TrieProofsSenderAfter[i][223][:],
			circuit.TrieProofsSenderAfter[i][224][:],
			circuit.TrieProofsSenderAfter[i][225][:],
			circuit.TrieProofsSenderAfter[i][226][:],
			circuit.TrieProofsSenderAfter[i][227][:],
			circuit.TrieProofsSenderAfter[i][228][:],
			circuit.TrieProofsSenderAfter[i][229][:],
			circuit.TrieProofsSenderAfter[i][230][:],
			circuit.TrieProofsSenderAfter[i][231][:],
			circuit.TrieProofsSenderAfter[i][232][:],
			circuit.TrieProofsSenderAfter[i][233][:],
			circuit.TrieProofsSenderAfter[i][234][:],
			circuit.TrieProofsSenderAfter[i][235][:],
			circuit.TrieProofsSenderAfter[i][236][:],
			circuit.TrieProofsSenderAfter[i][237][:],
			circuit.TrieProofsSenderAfter[i][238][:],
			circuit.TrieProofsSenderAfter[i][239][:],
			circuit.TrieProofsSenderAfter[i][240][:],
			circuit.TrieProofsSenderAfter[i][241][:],
			circuit.TrieProofsSenderAfter[i][242][:],
			circuit.TrieProofsSenderAfter[i][243][:],
			circuit.TrieProofsSenderAfter[i][244][:],
			circuit.TrieProofsSenderAfter[i][245][:],
			circuit.TrieProofsSenderAfter[i][246][:],
			circuit.TrieProofsSenderAfter[i][247][:],
			circuit.TrieProofsSenderAfter[i][248][:],
			circuit.TrieProofsSenderAfter[i][249][:],
			circuit.TrieProofsSenderAfter[i][250][:],
			circuit.TrieProofsSenderAfter[i][251][:],
			circuit.TrieProofsSenderAfter[i][252][:],
			circuit.TrieProofsSenderAfter[i][253][:],
			circuit.TrieProofsSenderAfter[i][254][:],
			circuit.TrieProofsSenderAfter[i][255][:],
			circuit.TrieProofsSenderAfter[i][256][:],
			circuit.TrieProofsSenderAfter[i][257][:],
			circuit.TriePathSenderAfter[i][:])
		trie_mimc.Validate256(api, hFunc, circuit.TrieRootHashesAfter[i],
			circuit.TrieProofsReceiverAfter[i][0][:],
			circuit.TrieProofsReceiverAfter[i][1][:],
			circuit.TrieProofsReceiverAfter[i][2][:],
			circuit.TrieProofsReceiverAfter[i][3][:],
			circuit.TrieProofsReceiverAfter[i][4][:],
			circuit.TrieProofsReceiverAfter[i][5][:],
			circuit.TrieProofsReceiverAfter[i][6][:],
			circuit.TrieProofsReceiverAfter[i][7][:],
			circuit.TrieProofsReceiverAfter[i][8][:],
			circuit.TrieProofsReceiverAfter[i][9][:],
			circuit.TrieProofsReceiverAfter[i][10][:],
			circuit.TrieProofsReceiverAfter[i][11][:],
			circuit.TrieProofsReceiverAfter[i][12][:],
			circuit.TrieProofsReceiverAfter[i][13][:],
			circuit.TrieProofsReceiverAfter[i][14][:],
			circuit.TrieProofsReceiverAfter[i][15][:],
			circuit.TrieProofsReceiverAfter[i][16][:],
			circuit.TrieProofsReceiverAfter[i][17][:],
			circuit.TrieProofsReceiverAfter[i][18][:],
			circuit.TrieProofsReceiverAfter[i][19][:],
			circuit.TrieProofsReceiverAfter[i][20][:],
			circuit.TrieProofsReceiverAfter[i][21][:],
			circuit.TrieProofsReceiverAfter[i][22][:],
			circuit.TrieProofsReceiverAfter[i][23][:],
			circuit.TrieProofsReceiverAfter[i][24][:],
			circuit.TrieProofsReceiverAfter[i][25][:],
			circuit.TrieProofsReceiverAfter[i][26][:],
			circuit.TrieProofsReceiverAfter[i][27][:],
			circuit.TrieProofsReceiverAfter[i][28][:],
			circuit.TrieProofsReceiverAfter[i][29][:],
			circuit.TrieProofsReceiverAfter[i][30][:],
			circuit.TrieProofsReceiverAfter[i][31][:],
			circuit.TrieProofsReceiverAfter[i][32][:],
			circuit.TrieProofsReceiverAfter[i][33][:],
			circuit.TrieProofsReceiverAfter[i][34][:],
			circuit.TrieProofsReceiverAfter[i][35][:],
			circuit.TrieProofsReceiverAfter[i][36][:],
			circuit.TrieProofsReceiverAfter[i][37][:],
			circuit.TrieProofsReceiverAfter[i][38][:],
			circuit.TrieProofsReceiverAfter[i][39][:],
			circuit.TrieProofsReceiverAfter[i][40][:],
			circuit.TrieProofsReceiverAfter[i][41][:],
			circuit.TrieProofsReceiverAfter[i][42][:],
			circuit.TrieProofsReceiverAfter[i][43][:],
			circuit.TrieProofsReceiverAfter[i][44][:],
			circuit.TrieProofsReceiverAfter[i][45][:],
			circuit.TrieProofsReceiverAfter[i][46][:],
			circuit.TrieProofsReceiverAfter[i][47][:],
			circuit.TrieProofsReceiverAfter[i][48][:],
			circuit.TrieProofsReceiverAfter[i][49][:],
			circuit.TrieProofsReceiverAfter[i][50][:],
			circuit.TrieProofsReceiverAfter[i][51][:],
			circuit.TrieProofsReceiverAfter[i][52][:],
			circuit.TrieProofsReceiverAfter[i][53][:],
			circuit.TrieProofsReceiverAfter[i][54][:],
			circuit.TrieProofsReceiverAfter[i][55][:],
			circuit.TrieProofsReceiverAfter[i][56][:],
			circuit.TrieProofsReceiverAfter[i][57][:],
			circuit.TrieProofsReceiverAfter[i][58][:],
			circuit.TrieProofsReceiverAfter[i][59][:],
			circuit.TrieProofsReceiverAfter[i][60][:],
			circuit.TrieProofsReceiverAfter[i][61][:],
			circuit.TrieProofsReceiverAfter[i][62][:],
			circuit.TrieProofsReceiverAfter[i][63][:],
			circuit.TrieProofsReceiverAfter[i][64][:],
			circuit.TrieProofsReceiverAfter[i][65][:],
			circuit.TrieProofsReceiverAfter[i][66][:],
			circuit.TrieProofsReceiverAfter[i][67][:],
			circuit.TrieProofsReceiverAfter[i][68][:],
			circuit.TrieProofsReceiverAfter[i][69][:],
			circuit.TrieProofsReceiverAfter[i][70][:],
			circuit.TrieProofsReceiverAfter[i][71][:],
			circuit.TrieProofsReceiverAfter[i][72][:],
			circuit.TrieProofsReceiverAfter[i][73][:],
			circuit.TrieProofsReceiverAfter[i][74][:],
			circuit.TrieProofsReceiverAfter[i][75][:],
			circuit.TrieProofsReceiverAfter[i][76][:],
			circuit.TrieProofsReceiverAfter[i][77][:],
			circuit.TrieProofsReceiverAfter[i][78][:],
			circuit.TrieProofsReceiverAfter[i][79][:],
			circuit.TrieProofsReceiverAfter[i][80][:],
			circuit.TrieProofsReceiverAfter[i][81][:],
			circuit.TrieProofsReceiverAfter[i][82][:],
			circuit.TrieProofsReceiverAfter[i][83][:],
			circuit.TrieProofsReceiverAfter[i][84][:],
			circuit.TrieProofsReceiverAfter[i][85][:],
			circuit.TrieProofsReceiverAfter[i][86][:],
			circuit.TrieProofsReceiverAfter[i][87][:],
			circuit.TrieProofsReceiverAfter[i][88][:],
			circuit.TrieProofsReceiverAfter[i][89][:],
			circuit.TrieProofsReceiverAfter[i][90][:],
			circuit.TrieProofsReceiverAfter[i][91][:],
			circuit.TrieProofsReceiverAfter[i][92][:],
			circuit.TrieProofsReceiverAfter[i][93][:],
			circuit.TrieProofsReceiverAfter[i][94][:],
			circuit.TrieProofsReceiverAfter[i][95][:],
			circuit.TrieProofsReceiverAfter[i][96][:],
			circuit.TrieProofsReceiverAfter[i][97][:],
			circuit.TrieProofsReceiverAfter[i][98][:],
			circuit.TrieProofsReceiverAfter[i][99][:],
			circuit.TrieProofsReceiverAfter[i][100][:],
			circuit.TrieProofsReceiverAfter[i][101][:],
			circuit.TrieProofsReceiverAfter[i][102][:],
			circuit.TrieProofsReceiverAfter[i][103][:],
			circuit.TrieProofsReceiverAfter[i][104][:],
			circuit.TrieProofsReceiverAfter[i][105][:],
			circuit.TrieProofsReceiverAfter[i][106][:],
			circuit.TrieProofsReceiverAfter[i][107][:],
			circuit.TrieProofsReceiverAfter[i][108][:],
			circuit.TrieProofsReceiverAfter[i][109][:],
			circuit.TrieProofsReceiverAfter[i][110][:],
			circuit.TrieProofsReceiverAfter[i][111][:],
			circuit.TrieProofsReceiverAfter[i][112][:],
			circuit.TrieProofsReceiverAfter[i][113][:],
			circuit.TrieProofsReceiverAfter[i][114][:],
			circuit.TrieProofsReceiverAfter[i][115][:],
			circuit.TrieProofsReceiverAfter[i][116][:],
			circuit.TrieProofsReceiverAfter[i][117][:],
			circuit.TrieProofsReceiverAfter[i][118][:],
			circuit.TrieProofsReceiverAfter[i][119][:],
			circuit.TrieProofsReceiverAfter[i][120][:],
			circuit.TrieProofsReceiverAfter[i][121][:],
			circuit.TrieProofsReceiverAfter[i][122][:],
			circuit.TrieProofsReceiverAfter[i][123][:],
			circuit.TrieProofsReceiverAfter[i][124][:],
			circuit.TrieProofsReceiverAfter[i][125][:],
			circuit.TrieProofsReceiverAfter[i][126][:],
			circuit.TrieProofsReceiverAfter[i][127][:],
			circuit.TrieProofsReceiverAfter[i][128][:],
			circuit.TrieProofsReceiverAfter[i][129][:],
			circuit.TrieProofsReceiverAfter[i][130][:],
			circuit.TrieProofsReceiverAfter[i][131][:],
			circuit.TrieProofsReceiverAfter[i][132][:],
			circuit.TrieProofsReceiverAfter[i][133][:],
			circuit.TrieProofsReceiverAfter[i][134][:],
			circuit.TrieProofsReceiverAfter[i][135][:],
			circuit.TrieProofsReceiverAfter[i][136][:],
			circuit.TrieProofsReceiverAfter[i][137][:],
			circuit.TrieProofsReceiverAfter[i][138][:],
			circuit.TrieProofsReceiverAfter[i][139][:],
			circuit.TrieProofsReceiverAfter[i][140][:],
			circuit.TrieProofsReceiverAfter[i][141][:],
			circuit.TrieProofsReceiverAfter[i][142][:],
			circuit.TrieProofsReceiverAfter[i][143][:],
			circuit.TrieProofsReceiverAfter[i][144][:],
			circuit.TrieProofsReceiverAfter[i][145][:],
			circuit.TrieProofsReceiverAfter[i][146][:],
			circuit.TrieProofsReceiverAfter[i][147][:],
			circuit.TrieProofsReceiverAfter[i][148][:],
			circuit.TrieProofsReceiverAfter[i][149][:],
			circuit.TrieProofsReceiverAfter[i][150][:],
			circuit.TrieProofsReceiverAfter[i][151][:],
			circuit.TrieProofsReceiverAfter[i][152][:],
			circuit.TrieProofsReceiverAfter[i][153][:],
			circuit.TrieProofsReceiverAfter[i][154][:],
			circuit.TrieProofsReceiverAfter[i][155][:],
			circuit.TrieProofsReceiverAfter[i][156][:],
			circuit.TrieProofsReceiverAfter[i][157][:],
			circuit.TrieProofsReceiverAfter[i][158][:],
			circuit.TrieProofsReceiverAfter[i][159][:],
			circuit.TrieProofsReceiverAfter[i][160][:],
			circuit.TrieProofsReceiverAfter[i][161][:],
			circuit.TrieProofsReceiverAfter[i][162][:],
			circuit.TrieProofsReceiverAfter[i][163][:],
			circuit.TrieProofsReceiverAfter[i][164][:],
			circuit.TrieProofsReceiverAfter[i][165][:],
			circuit.TrieProofsReceiverAfter[i][166][:],
			circuit.TrieProofsReceiverAfter[i][167][:],
			circuit.TrieProofsReceiverAfter[i][168][:],
			circuit.TrieProofsReceiverAfter[i][169][:],
			circuit.TrieProofsReceiverAfter[i][170][:],
			circuit.TrieProofsReceiverAfter[i][171][:],
			circuit.TrieProofsReceiverAfter[i][172][:],
			circuit.TrieProofsReceiverAfter[i][173][:],
			circuit.TrieProofsReceiverAfter[i][174][:],
			circuit.TrieProofsReceiverAfter[i][175][:],
			circuit.TrieProofsReceiverAfter[i][176][:],
			circuit.TrieProofsReceiverAfter[i][177][:],
			circuit.TrieProofsReceiverAfter[i][178][:],
			circuit.TrieProofsReceiverAfter[i][179][:],
			circuit.TrieProofsReceiverAfter[i][180][:],
			circuit.TrieProofsReceiverAfter[i][181][:],
			circuit.TrieProofsReceiverAfter[i][182][:],
			circuit.TrieProofsReceiverAfter[i][183][:],
			circuit.TrieProofsReceiverAfter[i][184][:],
			circuit.TrieProofsReceiverAfter[i][185][:],
			circuit.TrieProofsReceiverAfter[i][186][:],
			circuit.TrieProofsReceiverAfter[i][187][:],
			circuit.TrieProofsReceiverAfter[i][188][:],
			circuit.TrieProofsReceiverAfter[i][189][:],
			circuit.TrieProofsReceiverAfter[i][190][:],
			circuit.TrieProofsReceiverAfter[i][191][:],
			circuit.TrieProofsReceiverAfter[i][192][:],
			circuit.TrieProofsReceiverAfter[i][193][:],
			circuit.TrieProofsReceiverAfter[i][194][:],
			circuit.TrieProofsReceiverAfter[i][195][:],
			circuit.TrieProofsReceiverAfter[i][196][:],
			circuit.TrieProofsReceiverAfter[i][197][:],
			circuit.TrieProofsReceiverAfter[i][198][:],
			circuit.TrieProofsReceiverAfter[i][199][:],
			circuit.TrieProofsReceiverAfter[i][200][:],
			circuit.TrieProofsReceiverAfter[i][201][:],
			circuit.TrieProofsReceiverAfter[i][202][:],
			circuit.TrieProofsReceiverAfter[i][203][:],
			circuit.TrieProofsReceiverAfter[i][204][:],
			circuit.TrieProofsReceiverAfter[i][205][:],
			circuit.TrieProofsReceiverAfter[i][206][:],
			circuit.TrieProofsReceiverAfter[i][207][:],
			circuit.TrieProofsReceiverAfter[i][208][:],
			circuit.TrieProofsReceiverAfter[i][209][:],
			circuit.TrieProofsReceiverAfter[i][210][:],
			circuit.TrieProofsReceiverAfter[i][211][:],
			circuit.TrieProofsReceiverAfter[i][212][:],
			circuit.TrieProofsReceiverAfter[i][213][:],
			circuit.TrieProofsReceiverAfter[i][214][:],
			circuit.TrieProofsReceiverAfter[i][215][:],
			circuit.TrieProofsReceiverAfter[i][216][:],
			circuit.TrieProofsReceiverAfter[i][217][:],
			circuit.TrieProofsReceiverAfter[i][218][:],
			circuit.TrieProofsReceiverAfter[i][219][:],
			circuit.TrieProofsReceiverAfter[i][220][:],
			circuit.TrieProofsReceiverAfter[i][221][:],
			circuit.TrieProofsReceiverAfter[i][222][:],
			circuit.TrieProofsReceiverAfter[i][223][:],
			circuit.TrieProofsReceiverAfter[i][224][:],
			circuit.TrieProofsReceiverAfter[i][225][:],
			circuit.TrieProofsReceiverAfter[i][226][:],
			circuit.TrieProofsReceiverAfter[i][227][:],
			circuit.TrieProofsReceiverAfter[i][228][:],
			circuit.TrieProofsReceiverAfter[i][229][:],
			circuit.TrieProofsReceiverAfter[i][230][:],
			circuit.TrieProofsReceiverAfter[i][231][:],
			circuit.TrieProofsReceiverAfter[i][232][:],
			circuit.TrieProofsReceiverAfter[i][233][:],
			circuit.TrieProofsReceiverAfter[i][234][:],
			circuit.TrieProofsReceiverAfter[i][235][:],
			circuit.TrieProofsReceiverAfter[i][236][:],
			circuit.TrieProofsReceiverAfter[i][237][:],
			circuit.TrieProofsReceiverAfter[i][238][:],
			circuit.TrieProofsReceiverAfter[i][239][:],
			circuit.TrieProofsReceiverAfter[i][240][:],
			circuit.TrieProofsReceiverAfter[i][241][:],
			circuit.TrieProofsReceiverAfter[i][242][:],
			circuit.TrieProofsReceiverAfter[i][243][:],
			circuit.TrieProofsReceiverAfter[i][244][:],
			circuit.TrieProofsReceiverAfter[i][245][:],
			circuit.TrieProofsReceiverAfter[i][246][:],
			circuit.TrieProofsReceiverAfter[i][247][:],
			circuit.TrieProofsReceiverAfter[i][248][:],
			circuit.TrieProofsReceiverAfter[i][249][:],
			circuit.TrieProofsReceiverAfter[i][250][:],
			circuit.TrieProofsReceiverAfter[i][251][:],
			circuit.TrieProofsReceiverAfter[i][252][:],
			circuit.TrieProofsReceiverAfter[i][253][:],
			circuit.TrieProofsReceiverAfter[i][254][:],
			circuit.TrieProofsReceiverAfter[i][255][:],
			circuit.TrieProofsReceiverAfter[i][256][:],
			circuit.TrieProofsReceiverAfter[i][257][:],
			circuit.TriePathReceiverAfter[i][:])

		// verify the transaction transfer
		err := verifyTransferSignature(api, circuit.Transfers[i], hFunc)
		if err != nil {
			return err
		}

		// update the accounts
		verifyAccountUpdated(api, circuit.SenderAccountsBefore[i], circuit.ReceiverAccountsBefore[i], circuit.SenderAccountsAfter[i], circuit.ReceiverAccountsAfter[i], circuit.Transfers[i].Amount)
	}

	return nil
}

// verifySignatureTransfer ensures that the signature of the transfer is valid
func verifyTransferSignature(api frontend.API, t TransferConstraints, hFunc mimc.MiMC) error {

	// the signature is on h(nonce ∥ amount ∥ senderpubKey (x&y) ∥ receiverPubkey(x&y))
	hFunc.Write(t.Nonce, t.Amount, t.SenderPubKey.A.X, t.SenderPubKey.A.Y, t.ReceiverPubKey.A.X, t.ReceiverPubKey.A.Y)
	htransfer := hFunc.Sum()

	curve, err := twistededwards.NewEdCurve(api, tedwards.BN254)
	if err != nil {
		return err
	}

	hFunc.Reset()
	err = eddsa.Verify(curve, t.Signature, htransfer, t.SenderPubKey, &hFunc)
	if err != nil {
		return err
	}
	return nil
}

func verifyAccountUpdated(api frontend.API, from, to, fromUpdated, toUpdated AccountConstraints, amount frontend.Variable) {

	// ensure that nonce is correctly updated
	nonceUpdated := api.Add(from.Nonce, 1)
	api.AssertIsEqual(nonceUpdated, fromUpdated.Nonce)

	// ensures that the amount is less than the balance
	api.AssertIsLessOrEqual(amount, from.Balance)

	// ensure that balance is correctly updated
	fromBalanceUpdated := api.Sub(from.Balance, amount)
	api.AssertIsEqual(fromBalanceUpdated, fromUpdated.Balance)

	toBalanceUpdated := api.Add(to.Balance, amount)
	api.AssertIsEqual(toBalanceUpdated, toUpdated.Balance)

}
